### ISSUE TITLE
Shell variable expansion is fragile - remove it?

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#1]
(From http://rpmlint.zarb.org/cgi-bin/trac.cgi/ticket/51)

There are several ways to confuse the shell variable expansion routines in Pkg.py with perfectly valid and usual shell constructs. I'm having doubts that it's even worth a try to improve them - I find it unlikely that they could be made significantly better with sensible amounts of work.

Currently they serve little (pretty much cosmetic) purpose but may be the culprits of backtraces and inability to check some packages at all.

Should they be removed? Case in point:  https://bugzilla.redhat.com/210261

Original comment by: scop

**Comment by scarabeusiv** [comment]
This can be duped against issue #158 because we need to refactor it. Even tho this is way way older, lets keep the other one in place :)
