### ISSUE TITLE
Install in /usr/local 

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#10]
Hi there!

Your Makefile installs rpmdiff to /usr instead of /usr/local
when you build from source.

Could you please support installing to an arbitrary prefix and default to /usr/local?

This is good for us, distributors (in my case Debian).

Thanks.

Original comment by: aborrero

**Comment by scarabeusiv** [comment]
This got fixed by the migration to setuptools, as such it simply uses the default paths as passed on commandline.
