### ISSUE TITLE
"communication not allowed" error in the wrong format and has no explanation

### ISSUE THREAD

**Issue by farchord** [rpm-software-management/rpmlint#1008]
Building a package for Fedora gives the following error:

kde-inotify-survey.x86_64: E: communication not allowed /usr/share/dbus-1/system.d/org.kde.kded.inotify.conf

The error message is inconsistent with normal rpmlint errors (format-wise) and has no explanation.

Thanks!

**Comment by marxin** [comment]
Confirmed, you are right. I'm going to prepare a patch. When it comes to the explanation, I will likely need a help from @mgerstner. Am I right that it tells that there's no D-Bus rule that would allow a sending?

**Comment by marxin** [comment]
I'm going to change the check name in #1009 and I'm going to leave this issue for future improvement of the missing description text.

**Comment by mgerstner** [comment]
Yes it means that no one is allowed to talk to the service in question. Except root maybe?

This check is not part of the security related restrictions that we redesigned, it's general quality assurance. Adding a descriptive long description can be considered.

**Comment by marxin** [comment]
> Adding a descriptive long description can be considered.

Can you (or anybody familiar enough with D-Bus) do that, please?

**Comment by farchord** [comment]
Not sure if it helps, but this is the content of the file in question that triggered that error:

<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
 
  
  <policy user="root">
    <allow own="org.kde.kded.inotify"/>
  </policy>
 
</busconfig>
