### ISSUE TITLE
Reverse (keys vs values) _python_magic_values

### ISSUE THREAD

**Issue by socketpair** [rpm-software-management/rpmlint#103]
Since Pythons 3.5.2 and 3.5.3 have different magics. It may be desirable to reverse the dict.

Or, instead of reversing, make code changes to support tuple of magics (as well as single magic) for each Python version in this dict.

**Comment by scop** [comment]
I'm not sure we want to allow multiple values per X.Y Python version, see the extended description (`rpmlint -I python-bytecode-wrong-magic-value`). Unfortunately there doesn't seem to be a too good solution for this that I can think of right now. @davidmalcolm, thoughts?

**Comment by scop** [comment]
(BTW I think the magic value changed between 3.5.1 and 3.5.2, not 3.5.2 and 3.5.3.)

**Comment by davidmalcolm** [comment]
@scop, I'm rather out-of-the-loop on upstream CPython, sorry.

Note to self: the rpmlint test is implemented here:
https://github.com/rpm-software-management/rpmlint/blob/master/FilesCheck.py#L312

The current table of upstream CPython versions can be seen here:
https://github.com/python/cpython/blob/master/Lib/importlib/_bootstrap_external.py#L131

If I'm reading that table right, it looks like the 3.5 to 3.5.2 bump is the only time that a z-release has bumped the magic number on a released version.  Whether or not that's a good idea (it probably is for upstream CPython), there are now examples of .pyc files "in the wild" for each of the two magic numbers for the 3.5.* series.  

Bother.

I'm in two minds about what rpmlint should do:

- it could support multiple values per X.Y python version.
- it could insist on the latest version of the bytecode number, given the release (thus complaining about python packages built with the older version of 3.5.*)

I'm not sure what the best approach here is.

See also the note about PEP 3147 in the CPython link above - did they change the "magic tag" in CPython 3.5.2?

**Comment by davidmalcolm** [comment]
For reference, the upstream commit that added the new magic number:
https://github.com/python/cpython/commit/3c317e76a2fe78896b546e08fa753075463e7d41

Given that it's a bugfix; it implies that any .pyc build with the old magic number might be buggy (or might not be) - as far as I can tell, the bug only affects bytecode containing BUILD_MAP_UNPACK_WITH_CALL operations.

Given that, it *might* be best for rpmlint to only accept the new version.

**Comment by davidmalcolm** [comment]
Another upstream link: a table mapping *ranges* of .pyc magic numbers to CPython versions:
https://github.com/python/cpython/blob/master/PC/launcher.c#L1077
(for use on Windows, for handling double-clicking on .pyc files, I believe)

**Comment by socketpair** [comment]
Also note, for real-life:

old bytecode version + new python is OK (it works)
newer bytecode + old python is FAIL (don't work)

The problem may happen if someone builds RPM using Python 3.5.3, and try to install it on system where Python 3.5.2 is installed.

Myabe we should require `Requires: python >= 3.5.3`  if `.pyc`-files compiled using 3.5.3 magic ?

**Comment by stratakis** [comment]
Just a note here.
Python now accepts both magic numbers:
https://github.com/python/cpython/commit/93602e3af70d3b9f98ae2da654b16b3382b68d50

This patch is backported to F24 and F25 and we have updated the interpreter there as well to 3.5.3.

I would think that the best idea for rpmlint would be to support multiple magic numbers for a python version.
