### ISSUE TITLE
Does it make sense to release rpmlint as a pre-commit hook?

### ISSUE THREAD

**Issue by jpodivin** [rpm-software-management/rpmlint#1030]
Recently the `dnf5` project received set of basic pre-commit hooks to improve code consistency and overall dev experience.
A question was raised if rpmlint should be included among them. However, rpmlint hasn't been released as a hook yet, and it is a very specialized tool, intended to check build results, not necessarily the source. [1]  

Technically, only a minimal adjustment would be necessary to accomplish this result. But there is a question of fitness to the overall purpose of the project.

Example implementation: https://github.com/rpm-software-management/rpmlint/pull/1029 
@inknos 

[0] https://github.com/rpm-software-management/dnf5/pull/344
[1] https://github.com/rpm-software-management/dnf5/pull/344#issuecomment-1468038501

**Comment by danigm** [comment]
Closing this issue, the pre-commit hook config is in the main branch now https://github.com/rpm-software-management/rpmlint/blob/main/.pre-commit-hooks.yaml
