### ISSUE TITLE
rpmlint logo

### ISSUE THREAD

**Issue by kstreitova** [rpm-software-management/rpmlint#1052]
I was thinking for some time that the rpmlint project would definitely deserve some logo. I tried some of the free (in the trial) logo generators with "RPM", "linting", "cleaning" and similar keywords and it generated quite a nice logo. Maybe we could use it as an inspiration and create something out of it?

![rpmlint_logo](https://user-images.githubusercontent.com/9267383/232764916-8d9a4b34-b01e-426a-9d52-7fe44a7ab7be.png)

What do you think? Do you have any other ideas?

**Comment by Conan-Kudo** [comment]
That's a neat logo! 💯

**Comment by danigm** [comment]
I also think it's a nice logo, it could be used as it's or maybe adding RPM or rpmlint below or something like that.

**Comment by kstreitova** [comment]
Thank you for the feedback. Maybe I can ask our graphic designers to create a real logo out of it. Or if there is anybody with graphic skills they can rework it. I agree that we can add "rpmlint" below or next to the logo. 

What about the color? Do you see any color somehow connected to rpmlint already?

**Comment by marxin** [comment]
I also like the logo, thanks Kristýna!

**Comment by danigm** [comment]
![rpmlint](https://user-images.githubusercontent.com/50350/233275531-a4dfd1d4-4c85-492f-9efe-94382285974c.svg)

I've just converted the logo to a simple SVG.

**Comment by marxin** [comment]
The image is really cool and I would use it immediately. One small nit: I would prevent the tachometer from crossing letter `l` ;) But the trick that it's pivoted as the dot of `i` is smart.

**Comment by danigm** [comment]
I've just created a branch with the logo, so it's easier to modify and see the changes directly. I've tried to adapt the logo to make the circle small so the `l` doesn't touch it.

https://github.com/danigm/rpmlint/commit/3e8ef16108ab077e3cfd06e7b39339604a94966b#diff-f37a2f79efdd9535a4f9ca4da6a381d10995afeaf30de64cfb0f06b7d45029d8

**Comment by marxin** [comment]
Great, the logo is great and I would do a proper pull request.

**Comment by marxin** [comment]
@danigm I merged the logo but I forgot to notice that it's not used in README.md. Can you please do that?

**Comment by marxin** [comment]
> @danigm I merged the logo but I forgot to notice that it's not used in README.md. Can you please do that?

Done with 645b9b3462fe4721e9a454db574151abc47c9bcb.

**Comment by danigm** [comment]
> > @danigm I merged the logo but I forgot to notice that it's not used in README.md. Can you please do that?
> 
> Done with [645b9b3](https://github.com/rpm-software-management/rpmlint/commit/645b9b3462fe4721e9a454db574151abc47c9bcb).

Oh, thanks, I did that, but removed the commit from he PR when I cleaned a bit the svg file.
