### ISSUE TITLE
PythonCheck does not understand boolean requirements.

### ISSUE THREAD

**Issue by bnavigator** [rpm-software-management/rpmlint#1057]
Example: [python-jupyter-server-fileid](https://build.opensuse.org/package/show/devel:languages:python:jupyter/python-jupyter-server-fileid)

```specfile
Requires:       (python-jupyter-server >= 1.15 with python-jupyter-server < 3)
```

```
[  112s] python310-jupyter-server-fileid.noarch: W: python-missing-require jupyter-server
```

Related: #49

**Comment by danigm** [comment]
Yes, it's very basic right now, I'll try to improve to be a bit more "intelligent"
