### ISSUE TITLE
spelling-errors are not caught in spec files and in RPM packages without a language

### ISSUE THREAD

**Issue by ppisar** [rpm-software-management/rpmlint#1072]
rpmlint-2.4.0 (rpmlint-2.4.0-8.fc39 as found in Fedora) does not find misspellings at some places:

It seems it completely ignores %description and %description -l en when invoked on a spec file.
It seems it completely ignores %description (i.e. without a language specification) when invoked on a RPM package file.

See <https://lists.fedoraproject.org/archives/list/packaging@lists.fedoraproject.org/message/OXQEIMZTG4IWYXHQAWJSLXY5FRM3LKK7/> for an example.

**Comment by danigm** [comment]
I've started to work on a PR with some tests to verify that this problem is happening. It's a draft right now because there's no fix, just the tests.
