### ISSUE TITLE
Pytest Warnings in OpenSUSE distributions

### ISSUE THREAD

**Issue by afrid18** [rpm-software-management/rpmlint#1083]
Fedora distributions seems to be fine, but OpenSUSE Tumbleweed:Latest and OpenSUSE Tumbleweed:Latest no-optional-deps have many warnings, most are because of `magic` library as far as I know. Fedora:rawhide is exception, it been a week since its workflow broken #1082  .

Here is the brief summary of warnings in respective distributions:

-  Warnings in OpenSUSE Tumbleweed:Latest 
```
================= 366 passed, 894 warnings in 73.82s (0:01:13) =================
```

- Warnings in OpenSUSE Tumbleweed:latest, no-optional-deps
```
================ 334 passed, 32 skipped, 390 warnings in 14.29s ================
```

- Warnings in fedora:latest  **`No Warnings`** 
```
================== 362 passed, 4 skipped in 63.94s (0:01:03) ===================
```
- Warnings in fedora:latest, on-optional-deps **`No Warnings`** 
```
======================= 334 passed, 32 skipped in 18.64s =======================
```

This observation is taken from `main` branch GitHub Actions workflow, [ref](https://github.com/rpm-software-management/rpmlint/actions/runs/5461837541)

**Comment by danigm** [comment]
This should be easy to fix, we are using [detect_from_filename](https://github.com/rpm-software-management/rpmlint/blob/main/rpmlint/pkg.py#L359) from python-magic and that's deprecated, we should use `magic.from_file` instead. But the API is different, the old one returns an object with the `name` as an attribute, the new API returns the name directly.

```
def get_magic(path):
    try:
        return magic.from_filename(path)
    except ValueError:
        return ''
```

**Comment by danigm** [comment]
To make this compatible with libmagic python package, we can check at runtime with something like:

```
def get_magic(path):
    from_filename = None
    if hasattr(magic, 'from_filename'):
        # python-magic module
        from_filename = magic.from_filename
    else:
        # libmagic python bindings
        from_filename = magic.detect_from_filename
    try:
        return from_filename(path)
    except ValueError:
        return ''
```

**Comment by afrid18** [comment]
I think the problem is with the package that currently being used in workflow file. I have tinkered and resolved it by adding a pip install for `file-magic` and removing zypper package `python3-python-magic` which is actually not the intended one. I guess `file-magic` library is the one intended to be used from the first.

Ref [this](https://github.com/afrid18/rpmlint/actions/runs/5602847466/jobs/10248640342) workflow
Post resolving results are:


-  Warnings in OpenSUSE Tumbleweed:Latest **`No Warnings`** 
```
======================== 366 passed in 68.76s (0:01:08) ========================
```

- Warnings in OpenSUSE Tumbleweed:latest, no-optional-deps **`No Warnings`** 
```
======================= 334 passed, 32 skipped in 15.13s =======================
```

- Warnings in fedora:latest  **`No Warnings`** 
```
================== 362 passed, 4 skipped in 82.63s (0:01:22) ===================
```
- Warnings in fedora:latest, on-optional-deps **`No Warnings`** 
```
======================= 334 passed, 32 skipped in 14.68s =======================
```
- Warnings in fedora:rawhide **`No Warnings`** 
```
================== 362 passed, 4 skipped in 103.70s (0:01:43) ==================
```

**Comment by afrid18** [comment]
> To make this compatible with libmagic python package, we can check at runtime with something like:
> 
> ```
> def get_magic(path):
>     from_filename = None
>     if hasattr(magic, 'from_filename'):
>         # python-magic module
>         from_filename = magic.from_filename
>     else:
>         # libmagic python bindings
>         from_filename = magic.detect_from_filename
>     try:
>         return from_filename(path)
>     except ValueError:
>         return ''
> ```

While doing so, one testcase is having trouble, because the test case uses a string as a file path and python3-magic doesn't support any more extension based file type. It only requires a real file and real path.
