### ISSUE TITLE
check for leftover sphinx .doctrees

### ISSUE THREAD

**Issue by bmwiedemann** [rpm-software-management/rpmlint#1092]
For openSUSE, we want to ensure that the `.doctrees` subdir created by sphinx does not end up in the package, because it is only ephemeral data and non-deterministic (breaks reproducible builds)

**Comment by mcepl** [comment]
@danigm, @s-t-e-v-e-n-k Just thinking out aloud … another option would be to create `%sphinx_build` macro, which would make this clean up as well. Unfortunately, I am not sure whether Sphinx has enough stable even command line interface for that.

`rpmlint` check would be useful either way.

**Comment by danigm** [comment]
> @danigm, @s-t-e-v-e-n-k Just thinking out aloud … another option would be to create `%sphinx_build` macro, which would make this clean up as well. Unfortunately, I am not sure whether Sphinx has enough stable even command line interface for that.

I don't know, maybe that's a good idea, but checking for this I can see that [openstack has a macro with this name](https://github.com/openstack/rpm-packaging/blob/master/openstack/openstack-macros/macros.openstack-suse#L81), so it could collide, we can choose a different name.
 
> `rpmlint` check would be useful either way.

Yep, I'll add a new check to detect this, we can add it to the `PythonCheck.py`.
