### ISSUE TITLE
Warn if binary symlink is pointing to /usr/share/ and target is a script

### ISSUE THREAD

**Issue by darix** [rpm-software-management/rpmlint#1120]
it seems RPM then does not follow the symlink to find the shebang line.

see https://build.opensuse.org/request/show/1116460 -> https://bugzilla.opensuse.org/show_bug.cgi?id=1216028

**Comment by danigm** [comment]
What do you think it should be the rpmlint warning? If it detects a link in `/usr/bin` and the destination has a shebang the message could be something like:

*W: link-to-binary-with-shebang /usr/bin/gnome-characters is a link to a script with shebang, rpm won't be able to detect the dependency automatically.*

**Comment by darix** [comment]
well that would be one option. the other would be

`W: link-to-binary-with-shebang /usr/bin/gnome-characters is a link to a script but missing requires for /usr/bin/gjs-shell`

I mean we might also want to try to find out why rpm ignores symlinks to /usr/share when parsing shebang lines. but that is for a different bug.

**Comment by darix** [comment]
Thank you for the quick fix!
