### ISSUE TITLE
Moving *.py files to rpmlint directory

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/rpmlint#114]
There are *.py flies, and other kind of files in the top directory.

Shall we manage *.py files as `./rpmlint/*.py`?
This looks popular style according to below document.
http://docs.python-guide.org/en/latest/writing/structure/#the-actual-module

**Comment by scop** [comment]
I don't think popularity is a sufficient reason for making it harder to follow e.g. git history of a file.

Sometime rpmlint and its modules should probably be converted to a class/package hierarchy that is properly installed to site-packages, into rpmlint package, by setuptools etc. Then there would be a valid reason to restructure.
