### ISSUE TITLE
ruby.spec: W: more-than-one-%changelog-section

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpmlint#1161]
~~~
$ rpmlint ./ruby.spec /var/lib/mock/ruby/result/ruby-3.3.0-1.fc40.src.rpm 

... snip ...

ruby.spec: W: more-than-one-%changelog-section
ruby.spec:1: W: macro-in-%changelog %global
ruby.spec:2: W: macro-in-%changelog %global
ruby.spec:3: W: macro-in-%changelog %global
ruby.spec:4: W: macro-in-%changelog %global

... snip ...
~~~

I think the culprit actually is specifying multiple arguments, because running just `$ rpmlint ./ruby.spec` or `$ rpmlint /var/lib/mock/ruby/result/ruby-3.3.0-1.fc40.src.rpm` does not spit the warning.

~~~
$ rpm -q rpmlint
rpmlint-2.5.0-2.fc40.noarch
~~~

**Comment by danigm** [comment]
This could be caused because the same `Check` object is used several times for different files, so the state is not reset and that's why it's giving wrong errors.
