### ISSUE TITLE
Add option to fail on warnings/ignore certain findings

### ISSUE THREAD

**Issue by maximiliankolb** [rpm-software-management/rpmlint#1162]
Hi everyone!

I have two questions, maybe I can convert this issue into a RFE afterwards:

1. Is there a way to add a list of exceptions, maybe into a config file? Example: I would like to suppress warnings for `package.spec: W: invalid-url Source0: package.tar.gz`.
2. Is there a way to enforce "exit 1" if rpmlint reports any warnings (that are not in a list of exceptions)?

I have read the man-page and default config (e.g. ["BadnessThreshold"](https://github.com/rpm-software-management/rpmlint/blob/main/rpmlint/configdefaults.toml#L38C1-L38C17) is for errors, but not available for warnings). Unfortunately, I did not yet find any built-in solution.

For now, I could write stdout to a file, filter out expected/accepted warnings based on a regex, and then "exit 1" if the file still contains any lines.

Thanks :v:

**Comment by danigm** [comment]
To add a list of exceptions you can use the config file or rpmlintrc, for you example this rpmlintrc file should work:

```
addFilter('invalid-url Source')
```

For the second question, you can set custom score to different error names in the [Scoring section](https://github.com/rpm-software-management/rpmlint/blob/a79af73d2310a59dc730b6aa3ab8ffeeada82c5e/rpmlint/configdefaults.toml#L306C10-L306C10), or with the rpmlintrc file, for example:

```
setBadness('invalid-license', 1000)
```

Filters accept regular expression, the `setBadness` or the `Scoring` configuration is just error name and the new score, so you can convert errors to warnings with `setBadness('error', 0)` or convert warnings to errors with `setBadness('warning', 1000)` (`1000` is just to force retcode, default threshold is 999.
