### ISSUE TITLE
rpmlint override *.toml not blocking exec of a single filter rule ?

### ISSUE THREAD

**Issue by pgnd** [rpm-software-management/rpmlint#1170]
rpmlint's configs pull, by distro default (on Fedora 39, here), from
```
rpmlint ./test.spec
	...
	rpmlint: 2.5.0
	configuration:
		/usr/lib/python3.12/site-packages/rpmlint/configdefaults.toml
		/etc/xdg/rpmlint/fedora-legacy-licenses.toml
		/etc/xdg/rpmlint/fedora-spdx-licenses.toml
		/etc/xdg/rpmlint/fedora.toml
		/etc/xdg/rpmlint/scoring.toml
		/etc/xdg/rpmlint/users-groups.toml
		/etc/xdg/rpmlint/warn-on-functions.toml
	...
```

i want to *DISABLE* a check/rule; e.g.,
```
' mixed-use-of-spaces-and-tabs '
```

here, it's ENabled, in 'SpecCheck',
```
cat /usr/lib/python3.12/site-packages/rpmlint/configdefaults.toml
	# Enabled checks for the rpmlint to be run
	Checks = [
	...
	"SpecCheck",
	...
	]
	...
	# List of errors that can't be filtered
	BlockedFilters = []
	...
```

where
```
grep mixed-use /usr/lib/python3.12/site-packages/rpmlint/descriptions/SpecCheck.toml
	mixed-use-of-spaces-and-tabs="""
```

reading "https://github.com/rpm-software-management/rpmlint/blob/main/README.md"

	"...
	If you want to change configuration options or the list of checks you can use the following locations:

	/etc/xdg/rpmlint/*toml

	$XDG_CONFIG_HOME/rpmlint/*toml

	The configuration itself is a toml file where for some basic inspiration you can check up rpmlint/configdefaults.toml which specifies format/defaults.

	One can also include additional configuration files (or directories) by using the --config option. Note that all TOML configuration values are merged and not overridden. So e.g. values in a list are concatenated. If you need an override, use *.override.*toml configuration file, where all defined values are selected as default.
	"...

and, reading "https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html"

	"...
	If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.
	..."

here,
```
echo $XDG_CONFIG_HOME
	(empty)
```

so, i target 'SpecCheck.toml' for override
```
mkdir -p $HOME/.config/rpmlint/
cat << EOF > $HOME/.config/rpmlint/SpecCheck.override.toml
BlockedFilters = [
 ' mixed-use-of-spaces-and-tabs '
]
EOF
```

checking, the override _loads_ but with low order priority,
```
rpmlint ./test.spec
	rpmlint: 2.5.0
	configuration:
	    /usr/lib/python3.12/site-packages/rpmlint/configdefaults.toml
	    /etc/xdg/rpmlint/fedora-legacy-licenses.toml
	    /etc/xdg/rpmlint/fedora-spdx-licenses.toml
	    /etc/xdg/rpmlint/fedora.toml
	    /etc/xdg/rpmlint/scoring.toml
	    /etc/xdg/rpmlint/users-groups.toml
	    /etc/xdg/rpmlint/warn-on-functions.toml
->	    /root/.config/rpmlint/SpecCheck.override.toml
	checks: 32, packages: 1
```

and the test still fires
```
test.spec:24: W: mixed-use-of-spaces-and-tabs (spaces: line 24, tab: line 2)
====== 0 packages and 1 specfiles checked; 0 errors, 1 warnings, 1 filtered, 0 badness; has taken 0.8 s ======
```
what's correct config/usage to override that single rule ?
different config or different path than i've used?

**Comment by danigm** [comment]
If you want to disable a rule you should use the `Filters` configuration. As the comment says, `BlockedFilters` is `# List of errors that can't be filtered`

**Comment by pgnd** [comment]
my bad. read that to mean *won't be*.

`Filters = [...]` in `~/rpmlint/fedora.toml` does the trick, and _does_ filter the check out.

```
====== 0 packages and 1 specfiles checked; 0 errors, 0 warnings, 1 filtered, 0 badness; has taken 0.9 s ======
```
o/
