### ISSUE TITLE
Noarch RPMs that contain eBPF binaries incorrectly marked with arch-independent-package-contains-binary-or-object

### ISSUE THREAD

**Issue by socketpair** [rpm-software-management/rpmlint#1193]
Fixed in RPM itself:
https://github.com/rpm-software-management/rpm/issues/2875

**Comment by danigm** [comment]
Could you provide an example .rpm or a test to replicate this problem easily?

The check is [done here](https://github.com/rpm-software-management/rpmlint/blob/main/rpmlint/checks/BinariesCheck.py#L678).

I think that the main problem is that the [elf regex](https://github.com/rpm-software-management/rpmlint/blob/main/rpmlint/checks/BinariesCheck.py#L38) matches the eBPF binaries and we don't have any special check to differentiate this files from other binaries.

**Comment by socketpair** [comment]
Canonical .spec-file for such RPM is here:
https://github.com/rpm-software-management/rpm/pull/2902/files
