### ISSUE TITLE
RFE: accept also "$(dirname "$specfile")/.rpmlintrc" config file

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/rpmlint#125]
Seems like only .rpmlintrc from home directory has been accepted so far, but it would be nice to be able to ignore rpmlint  warnings on per-package basis.

**Comment by praiskup** [comment]
For security reasons, `.rpmlintignore` with list of regular expressions would be a better approach?

**Comment by Conan-Kudo** [comment]
I don't want any dotfiles for this. They should be fully visible. My feeling is that it should be `<srcpkgname>.rpmlintrc`.

As for where the file is or its name, as far as I'm aware, rpmlint itself doesn't care. This is up to the tools that automatically run rpmlint.

**Comment by praiskup** [comment]
Dotfile is perfectly fine with me... it is low priority file which not everyone is interested in;
same as pylintrc, .gitignore, etc.

Though it shouldn't be python "evaluated" file, since it is insecure.  One could get malicious
code executed without noticing.

**Comment by scarabeusiv** [comment]
I wrote logic for loading old configs here https://github.com/rpm-software-management/rpmlint/pull/151/commits/699ec5e4981c6a4fa2f3e3a3d0af69fcaa54ec9e

Possible question is if the rpmlint should do this on its own or if we leave it as another config passed as -f. If changes to be done should go when doing issue#155.

**Comment by scarabeusiv** [comment]
Hmm now one of the interesting thing is, if we run rpmlint on some list of items where should the found rpmlint files apply.

`path/file1.rpm`
`path/file1-rpmlintrc`
`path2/file2.rpm`

In the above scenario should the rpmlintrc be applied on the `path2/file2.rpm`?

Also alternatively:

`path/file1.rpm`
`path/file1-rpmlintrc`
`path/file2.rpm`
`path/file3.rpm`
`path/file3-rpmlintrc`

Should the rpmlints in the above merged and applied for everything?

**Comment by Conan-Kudo** [comment]
I would expect we'd apply rules based on source package name rpmlintrc files. But if we were reading multiple files, I guess it would merge them as you say.

**Comment by praiskup** [comment]
Well, I'm repeating myself :-) but I still think `.rpmlintrc` file near the spec file (in dist-git it would be stored along the `.gitignore` file) is better idea.  Rpmlint can then simply look into the directory where where the linted file is (be that spec or srpm file), and check for dotfile.

Anything else sounds a bit overcomplicated to me.

**Comment by Conan-Kudo** [comment]
I think making it a dotfile is probably a bad idea, and leaving it as `<srcpkgname>.rpmlintrc` is sufficient. But I could see supporting _either_ `.rpmlintrc` or `<srcpkgname>.rpmlintrc` with the latter taking precedence over the former.

**Comment by praiskup** [comment]
Agreed, btw., there might be global option `accept_dotfile = False` by default.

Btw., the `srcpkgname` is sometimes non deterministic (SCLs, it depends on %scl being defined or not).

**Comment by Conan-Kudo** [comment]
@praiskup SCL packaging shouldn't mutate the source package...

**Comment by scarabeusiv** [comment]
Yea looking more at the stuff we will simply have to process all rpmlintrcs that are found during parsing because otherwise it gets really crazy to interpret what rpmlint goes where sadly. Of course best results are achieved if you won't run rpmlint against your whole darn distro ;-)

**Comment by praiskup** [comment]
@Conan-Kudo unfortunately, %scl macro is in `Name` tag.  So it does mutate the srpm filename.

**Comment by praiskup** [comment]
Of course rpmlint can look at "spec" filename inside srpm, that can not be affected by macro expansion.

**Comment by scarabeusiv** [comment]
Yeah with the lookup logic you would have to keep a list of all rpmlintrc files and then during run compare them with the final 'name' that you need to dig out and either apply the thing to the checks or not. Also we would have to have a function that extracts the name first too, as you can check normal rpms generated from srpm where you need to get the srpm name from the metadata info too...

I would say I will load them as they are found and people must be sane to not run rpmlint on too many files at once as they would each append their rpmlintrc.

TBH I still expect common usecase is to be rpmlint on the built packages to see how they cope so there sould be nothing more over the single src.rpm and its built results...

**Comment by praiskup** [comment]
I won't pretend I'm not lost, this got twisted from a few-liner patch into
complicated thing, hm.  Maybe not?

My original idea was to make rpmlint non-annoying for common Fedora
packager - so packagers can provide (some) blacklist file.  The blacklist
file needs to live as close to spec file as possible (along the spec file
in dist-git), otherwise it is useless.  Plus rpmlint should treat the
blacklist automatically if present, ideally on every single maintainer's
box -- otherwise, even though I specified the blacklist (and I have
properly configured rpmlint == silence on my box), people will keep
consistently claim that my package did not pass rpmlint and it must be
broken.  CI will likely claim that as well (I almost never look at rpmlint's
output in bodhi, sorry).

Normally, when I do `ls` in package's git repo, I see `sources` and
`<package>.spec`.  I don't think that something as verbose as
`<package>.rpmlintrc` would be easily accepted by packagers (ditracting),
when people are used to work with dotfiles.

**Comment by scarabeusiv** [comment]
I will tweak it to accept the semantic we have in OBS, see:
  https://build.opensuse.org/package/show/X11:xfce/thunar

I will load up `<WHATEVER>rpmlintrc` and see how that goes.

I even don't think that hiding it in dotfiles is a good idea because you want it to be obvious that someone did overrides for the rpmlint report (eg someone sneaking in stuff on the first review by disabling things).

**Comment by praiskup** [comment]
On Thursday, September 19, 2019 9:45:18 AM CEST Tomáš Chvátal wrote:
> (eg someone sneaking in stuff on the first review by disabling things).

There's just spec + src.rpm in fedora review request.

**Comment by Conan-Kudo** [comment]
@scarabeusiv I don't want it to accept `<whatever>rpmlintrc`. That's dangerous and crazy.

**Comment by Conan-Kudo** [comment]
@praiskup Not everyone does package reviews that way. openSUSE does spec + patches + rpmlintrc (if one exists).

**Comment by scarabeusiv** [comment]
Commit merged in for 2.0 release.
