### ISSUE TITLE
rpmlint decided that this file is an executable

### ISSUE THREAD

**Issue by mcepl** [rpm-software-management/rpmlint#126]
It has has mode 644 (and it is not compressed in reality, I have gzipped this, just so that it can be attached here).
[README.gz](https://github.com/rpm-software-management/rpmlint/files/1736848/README.gz)

**Comment by scarabeusiv** [comment]
Add minimal rpm file here exhibiting the issue:

https://github.com/rpm-software-management/rpmlint/tree/master/test/binary

Then put test in test/test_files.py where just copy the behaviour ie from test_python_bytecode_magic.

**Comment by mcepl** [comment]
It comes from https://build.opensuse.org/package/show/Publishing/lout (see [_log.txt](https://github.com/rpm-software-management/rpmlint/files/3435679/_log.txt)).

**Comment by scarabeusiv** [comment]
Interestingly if I just copy that file out the rpmlint does not mark it as such... Only in the pacakge itself...

**Comment by marxin** [comment]
The file has really `+x` set:

```
[   52s] + /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
[   52s] patching file makefile
[   52s] + chmod -x README
[   52s] + exit 0
```

When I extract the file out of package I see:
```
l ./usr/share/lout/doc/user/README
-rw-r--r-- 1 marxin users 2147 Nov 12  2018 ./usr/share/lout/doc/user/README
```

**Comment by mcepl** [comment]
OK, @marxin is right. I am an idiot.
