### ISSUE TITLE
openSUSE: strict policy to ERR on patch-macro-old-format

### ISSUE THREAD

**Issue by DimStar77** [rpm-software-management/rpmlint#1272]
openSUSE Tumbleweed has eliminated all usages of `patch-macro-old-format`

In order to ensure no new usages are creeping in unnoticed, we'd like to see E: 10000 to enforce this policy from this point forward.

**Comment by DimStar77** [comment]
CC @danigm

**Comment by danigm** [comment]
I've created the PR for the main branch, then we can merge the change in the opensuse one to get this change in Tumbleweed.
