### ISSUE TITLE
Dropping Python 2 support

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/rpmlint#143]
Python 2 will be EOL/EOS by PSF on January 1, 2020.

Today, rpmlint is Python 2/Python 3 compatible, but Python 2 restricts us from making some interesting enhancements to improve rpmlint.

A survey of the top Linux distributions using RPM indicates the following:

|    Distribution    | RPM Version | RPMLint version | Python 3 available | RPM bindings for Python 3 available |
|--------------------|-------------|-----------------|--------------------|-------------------------------------|
| Fedora Rawhide     |      4.14.1 |            1.10 | Yes                | Yes                                 |
| Fedora 28          |      4.14.1 |            1.10 | Yes                | Yes                                 |
| Mageia Cauldron    |      4.14.1 |            1.10 | Yes                | Yes                                 |
| Mageia 6           |      4.13.1 |             1.5 | Yes                | Yes                                 |
| openSUSE Leap 15.x |      4.14.1 |            1.10 | Yes                | Yes                                 |
| openSUSE Leap 42.x |      4.11.2 |             1.8 | Yes                | Yes                                 |
| CentOS 7           |      4.11.3 |             1.5 | No (EPEL/SCL only) | No                                  |

CentOS 7 (and thus RHEL 7) is the only distribution on this list that doesn't offer Python 3 with RPM bindings for Python 3. However, Red Hat Enterprise Linux 8 will _only_ offer Python 3, per [this deprecation notice](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.5_release_notes/chap-red_hat_enterprise_linux-7.5_release_notes-deprecated_functionality#idm140090689468304). SUSE already did this with the release of SUSE Linux Enterprise 15 this year.

At this point, we should target the next release to support only Python 3, probably calling it version 2.0 to indicate the support breakage.

**Comment by dirkmueller** [comment]
I would suggest to do a release of the current state prior removing python 2.x support. There are a ton of small bugfixes that haven't been released and both setuptools as well as moving to python 3
.x only is some reworking that will take some time.

So my suggestion instead of 'remove it for the next release' my suggestion is to remove it 'after' the next release, and do the release from current state asap.

**Comment by dirkmueller** [comment]
+1 on the plan overall, it is time to cut out python 2.x support after the next release.

**Comment by Conan-Kudo** [comment]
Python 2 support has been dropped in b8b78ec002599c8145488fa208f3e668d0b7a802.
