### ISSUE TITLE
Cleanup after tests

### ISSUE THREAD

**Issue by scarabeusiv** [rpm-software-management/rpmlint#148]
When messing around with the tests I just noticed we happen to leave around quite a mess in /tmp we should be polite and cleanup.

**Comment by scarabeusiv** [comment]
Actually after digging out we have ExtractDir config option that defaults to tmpfiles generator if not defined, yet it is not used actively among most of the tests -> this will need to be tweaked up.

**Comment by mimi1vx** [comment]
partially fixed in #366

**Comment by scarabeusiv** [comment]
It is fixed in the end by f07832035bf647081e33a5981da1c0a3d1111628
