### ISSUE TITLE
Add configurations for rpm distros and test them

### ISSUE THREAD

**Issue by scarabeusiv** [rpm-software-management/rpmlint#157]
Have rpmlint defaults for all major distros Fedora/SUSE/Mageia/etc.
With that make sure we can verify the behaviour of rpmlint stays sane with whatever config we loaded.
Also we can this way have distro specific tests validated when we load the desired config.

This could make ie openSUSE rpmlint-checks and test repository merged here while not adding extra burden for the other distributions.

**Comment by Conan-Kudo** [comment]
So this probably wouldn't be too difficult to do for Fedora and Mageia, since both distributions use the base set of checks and contribute their check extensions upstream, but openSUSE would be very difficult at present.

**Comment by scarabeusiv** [comment]
Yep I will simply add the suse checks and add the tests, there is no actual reason to not have them here as they simply won't be imported, and if anyone decides to import them they can.

Also with that we can be safe in expecting that the distros can use the rpmlint right away without any excessive patching, and I know we have ton of it in openSUSE...

**Comment by marxin** [comment]
@scarabeusiv I would close this issue.

**Comment by scarabeusiv** [comment]
Yep looks complete for openSUSE, other distros can add theirs if they need tweaking from defaults.
