### ISSUE TITLE
rpmlint could check that -devel are in a development group

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#17]
This would be nice for the users to not get -devel packages in the list when they search for a kind of app.

Changed 7 years ago by misc 

We should have something more generic. Ie, checking that perl-\* are in Developement/perl, etc.

But then arise the issue of configurating this check. The same system should be used for NamingPolicy? check, and we should avoid hardcoded check.

Changed 7 years ago by scop 

misc's comment seconded. One possible implementation would be to add a config dict like { regexp: group } and check that package names matching "regexp" have "group" as their group tag. And maybe make "group" a regexp too.

Original comment by: scop

**Comment by scop** [comment]
Patch from original ticket: https://gist.github.com/scop/3080ec1b86fa24f5e012

**Comment by keszybz** [comment]
Groups are obsolete... at least in Fedora. Maybe this can be closed?

**Comment by scarabeusiv** [comment]
Groups are dead, even in SUSE now. Closing...
