### ISSUE TITLE
DocFilesCheck.py - GPL2.0 only

### ISSUE THREAD

**Issue by scarabeusiv** [rpm-software-management/rpmlint#179]
We have whole package licensed as GPL-2.0+ yet DocFilesCheck states itself as gpl-2.0-only and there is no way to contact the author of it (dead emails everywhere).

As such someone should rewrite it in order to have the whole rpmlint under one license only.

**Comment by dirkmueller** [comment]
I found a working email address and asked for relicensing.

**Comment by ensc** [comment]
I am ok with relicensing to GPL-2.0+.

**Comment by scarabeusiv** [comment]
Splendid, thank you!

**Comment by Conan-Kudo** [comment]
This was fixed a while ago...
