### ISSUE TITLE
Switch configuration from ConfigObj to TOML

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/rpmlint#182]
ConfigParser is a somewhat wobbly format for configuration, and it gets tricky for dealing with some of the config we actually have in here.

I'd like for us to change our configuration settings from configparser to [TOML](https://github.com/toml-lang/toml) using [tomlkit](https://github.com/sdispater/tomlkit) to simplify things.

**Comment by scarabeusiv** [comment]
I am fine with that, now that the whole thing is covered in tests it should be quite okay, I just never used toml, and the configparser I used because it was used by openstack stuff.

**Comment by Conan-Kudo** [comment]
The Python and Rust communities seem to be moving towards preferring it for "simple" configuration (which I admit, I'd like to have rpmlint's configuration be simple).

**Comment by scarabeusiv** [comment]
Well i already reduced the stuff that could've been configured :P
But anyway it could be done, as long as we can keep the dictionary internal stucture we are fine.

**Comment by Conan-Kudo** [comment]
Internal representation of TOML is JSON-like, so I don't see a problem with being able to maintain that.

**Comment by mcepl** [comment]
Well, just that's another external dependency. What's so wrong with ``configparser`` (or JSON for that matter) exactly? “It is going out of fashion” doesn't seem like a sensible reason to me.

**Comment by Conan-Kudo** [comment]
The issue with configparser vs TOML is that the former has slightly undefined behavior. It also makes it easier for other tools to be able to reliably parse and generate our configuration programmatically, since we're using a fully defined configuration format.

**Comment by scarabeusiv** [comment]
Well the most important part is that we use ConfigObj from cloud peepz and it is bit dead compared to TOML.
Sadly direct usage of configparser sucks in storing arrays and subclasses.

**Comment by mcepl** [comment]
JSON?

**Comment by scarabeusiv** [comment]
Well take look on the structure and testsamples, we have to either have per module config or subclasses.

**Comment by scarabeusiv** [comment]
Commited in.
