### ISSUE TITLE
rpmdiff leaves behind two temporary directories when comparing source RPMs

### ISSUE THREAD

**Issue by scfc** [rpm-software-management/rpmlint#190]
When running `rpmdiff /path/to/1/pkg.src.rpm /path/to/2/pkg.src.rpm`, `rpmdiff` leaves behind two temporary directories `/tmp/rpmlint.pkg.src.rpm.$random`.  These directories should be removed when `rpmdiff` finishes.

This may be a duplicate of issue #148.

**Comment by scarabeusiv** [comment]
Yep, that is exactly the same thing, the pkg.py is really weirdly managing its tempfolders, but without the refactoring being finished it does not make sense to track it twice so I shall close your ticket for now.
