### ISSUE TITLE
Investigate usage of pyelftools for binary checks

### ISSUE THREAD

**Issue by marxin** [rpm-software-management/rpmlint#192]
https://github.com/eliben/pyelftools

**Comment by marxin** [comment]
@scarabeusiv

**Comment by scarabeusiv** [comment]
As I discussed with Martin we need to check up if we could use something python-ish rather than sticking to calling readelf in binaryinfo object. So lets try that.

**Comment by scarabeusiv** [comment]
Martin is now looking in redoing the binariescheck to have better approach to this.

**Comment by marxin** [comment]
Yes, I'm working on that. However, I'm planning to stay with the current instrumentation for `readelf` utility.

**Comment by scarabeusiv** [comment]
If that works beter I am okay with that. Simply we will close this bug at the point we have binarycheck that we are happy with.

**Comment by marxin** [comment]
Now I am happy wirh that.
