### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpmlint#198]
https://github.com/rpm-software-management/rpmlint/blob/0736424e8bc8ccfec16765458d21df059ba2f2a1/scripts/lint.py#L74

This line can cause an exception if certain conditions are met.

If I run rpmlint in mock that doesn't have all locales by default and my locale is not explicitly installed into that mock, I get:

```
>>> import locale
>>> locale.setlocale(locale.LC_COLLATE, '')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

This is the commit that added the line:

6f4af3cd65b0ccdab7455e3fbe8ff9947b979d39

It says "Process installed packages matched by a wildcard in locale's alphabetic order" yet it doesn't really explain why we want to do that. Anyway, I think that if we cannot do that, rpmlint should not crash but rather fallback to default sorting.

I'll submit a PR that wraps it in `contextlib.suppress`.

**Comment by hroncok** [comment]
https://github.com/rpm-software-management/rpmlint/pull/199

**Comment by dnsmichi** [comment]
A workaround is to install the `glibc-langpack-en` as noted here: https://github.com/CentOS/sig-cloud-instance-images/issues/71#issuecomment-549068200 (for everyone hitting this issue via Google).
