### ISSUE TITLE
Move the description dictionaries from code to toml files aside

### ISSUE THREAD

**Issue by scarabeusiv** [rpm-software-management/rpmlint#222]
This will ease the logic in the packages where we can faster load just all the yamls when showing explanations.

Ie rpmlint/checks/ZipCheck.py + rpmlint/checks/ZipCheck.yaml which will contain the descriptions.

Also it will shorten the code of the tests as this huge blob with strings will be elsewhere.

For testing we will have to validate that all short abbrevations have some descriptions and error out if there are some explanations missing.

**Comment by Conan-Kudo** [comment]
@scarabeusiv Wait, why YAML? We just got TOML implemented, why also add YAML?

**Comment by scarabeusiv** [comment]
@Conan-Kudo yeah toml would work as well, I am still torn about the final implementation TBH.

If it should be bazilion of small files or one file containing info for all tests.

And we should have a test in place that verifies that all warnings have a description.
