### ISSUE TITLE
Review and close/merge all the currently open PRs that are from 2018 and older

### ISSUE THREAD

**Issue by scarabeusiv** [rpm-software-management/rpmlint#226]
We shouldn't keep up PRs open if they won't be merged. I closed those that are not even remotely applicable anymore but there are still ~8 that need review and some cherry-picking as they look useful.

**Comment by scarabeusiv** [comment]
Done

**Comment by Conan-Kudo** [comment]
Not quite, as I reopened one to remind myself to port over...

**Comment by scarabeusiv** [comment]
As there is just one left over and it is tagged to the milestone we don't need two tickets for one problem.
