### ISSUE TITLE
Syntax check in 'spec' file

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#24]
Hi,

Some syntax errors in the **spec** file that are not recognized by **rpmlint**, causes problems when we try to remove the package.
But then it is often too late and it can only be solved after a **_yum reinstall**_ or **_rpm -i --replacepkgs**_ of the improved rpm.

example :
&nbsp;\- <span style="color:red;">erroneously</span>:
<code>&nbsp;&nbsp;&nbsp;&nbsp;%preun
&nbsp;&nbsp;&nbsp;&nbsp;if [ $1 = 0 ] <span style="color:red;">**:**</span> then
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/sbin/install-info --delete %{_infodir}/%{name}.info %{_infodir}/dir || :
&nbsp;&nbsp;&nbsp;&nbsp;fi</code><br>&nbsp;-<span style="color:blue;">correct</span>:
<code>&nbsp;&nbsp;&nbsp;&nbsp;%preun
&nbsp;&nbsp;&nbsp;&nbsp;if [ $1 = 0 ] <span style="color:blue;">__;__</span> then
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/sbin/install-info --delete %{_infodir}/%{name}.info %{_infodir}/dir || :
&nbsp;&nbsp;&nbsp;&nbsp;fi</code>
- the error when we try to remove the pakage (via yum or rpm): **syntax error near unexpected token `fi**
- version: rpmlint-1.5-9.fc19.noarch

Again: **rpmlint**, **rpmbuild** and the **yum (local)install** happens flawless.

I know that removing a package would be a standard test procedure. But still.
What is the cost if we want to add this and similar syntax checks?

Regards

Original comment by: kdg1955

**Comment by scarabeusiv** [comment]
This looks like nothing should really be done here, it scans the stuff and reports issues as seen.
