### ISSUE TITLE
Potential errant output when calling rpm.expandMacro in TagsCheck.py

### ISSUE THREAD

**Issue by jasontibbitts** [rpm-software-management/rpmlint#262]
In https://bugzilla.redhat.com/show_bug.cgi?id=1628465 is a complaint that depending on what packages are installed, rpmlint might cause some weird complaints when asked to check anything at all.

The specific issue there is that when `TagsCheck.py` is loaded, `rpm.expandMacro('%python_sitearch')` will get called and that will cause rpm to emit an error trying to exec `/usr/bin/python` if (on Fedora) the `python-unversioned-command` package is not installed.

Macros like `%ruby_sitearch` don't cause the same issue because those macros aren't even defined when the corresponding packages aren't installed.  In Fedora, one package provides the relevant macros for all python versions.

Potential fixes within rpmlint:
* Just drop `%python_sitearch` from the list; on Fedora at least it won't ever give any additional directories that `%python2_sitearch` and `%python3_sitearch` don't produce.
* Make the list of macros configurable somehow so distros can include their own preferred list without having to patch rpmlint.
* Wrap `rpm.expandMacro` with a utility function that sends erors to `/dev/null` so that errant RPM output doesn't show up in rpmlint's output.  (Though this could potentially hide useful information.)
* Maybe not rely on what's installed at the time rpmlint is run to determine `private_so_paths` and just require that the distribution make sure the list is configured correctly.

I guess Fedora could also perhaps make the macros be quiet when the executable isn't there, but then that unconditionally suppresses what can be useful error output.  We might even like to make them error but that might do worse things to rpmlint.

I might find the time to work on one of those options if I had some idea about which would be most desirable.

**Comment by scarabeusiv** [comment]
We removed the code as it caused trouble on openSUSE too. Possible reimplementation tracked at #339
