### ISSUE TITLE
Add badness scoring support

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#27]
(From http://rpmlint.zarb.org/cgi-bin/trac.cgi/ticket/70)

the patch below adds an optional new feature: possibility to assign a badness score to each individual check. The feature, if used, modifies the behaviour of rpmlint. Then by default each check is degraded to a warning, and only checks which have a badness assigned become an error. In addition, it cumulates the errors and exits with nonzero exit code if a threshold is exceeded. This allows an easy customisation for distributions.

The patch in addition changes output behavior to group checks together and only print the --info information once for each check (previously it did that for each check in particular, which printed a lot of redundant text).

if no badness is configured, previous behavior is preserved.

Changed 6 years ago by misc 

Sorry for now looking earlier, but the patch seems quite incomplete, or I am wrong ?

Changed 5 years ago by dmueller@…

attachment add-scoring-support.2.diff   added
updated patch (rediffed against 0.82)

Changed 5 years ago by misc 

keywords patch added
Changed 5 years ago by scop 

owner changed from misc@… to scop
status changed from new to assigned
Modified version applied in [1426], thanks. I changed the config option to BadnessThreshold? and without understanding the intent properly, probably broke the info message grouping feature - that'll have to be redone. Leaving open for that (and help is welcome!).

Regarding the incomplete looking patch - trac's HTML diff viewer sucks for multifile diffs, it seems to often show only changes for the first file. Download the patch in original format to view it completely.

Original comment by: scop

**Comment by scop** [comment]
Patch from original ticket: https://gist.github.com/scop/33b683fd88cd0748814f

**Comment by scarabeusiv** [comment]
Looking on the code the badness evaluation was added at least in 79ac90bb as the test is present there, probably even sooner.
