### ISSUE TITLE
RFE: overrides

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#28]
Hi there!

rpmlint is a great tool.

In some environments, rpmlint reports some problems that are mandatory for a given package.

For example, it reports that `cp' and`install' commands in %post are 'dangerous'.
I understand that are dangerous, but some times they are necessary: for example, a custom RPM package for configuration (and this configuration implies moving files).

A possible workaround for rpmlint is to add overrides support, like lintian does in the debian world.

In lintian, you create a file with this format (approximate):
===8<===
# comment

package: lintian-tag
# comment

package: lintian-tag2
===8<===

This file is later packaged in the resulting .deb file, and lintian doesn't report (unless explicitly required) those tags.

I guess we can do the same:
- look for a packaged file:
  /usr/share/doc/<package>/rpmlint-overrides
- scan for tags in the file:
  ===8<===
  # the install cmd is needed!
  
  package.noarch: W: dangerous-command-in-%post install
  ===8<===
- do the checks, but ignore 'dangerous-command-in-%post'

Would you consider this enhancement?

Thanks, regards.

Original comment by: aborrero

**Comment by scarabeusiv** [comment]
Was closed previously on SF as wontfix.
