### ISSUE TITLE
Check pkgconfig files

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#30]
(From http://rpmlint.zarb.org/cgi-bin/trac.cgi/ticket/81, dmueller@…)

the check below should be a start for a pkgconfig file checkier

Changed 6 years ago by scop 

Checking for build root strings in installed files is very useful, but it is not at all limited to pkgconfig files, therefore I think this check should not be applied as is.

Also, FWIW, rpm 4.4.2.1 from rpm.org includes a "check-buildroot" script that can be used to cause the package build to fail if (almost) any of the installed files contains the build root string. That's IMO a better approach than having the check in rpmlint, but of course having it in rpmlint is useful for packages built without the check.

Changed 6 years ago by dmueller@… 

I know that there are other places where this is already checked. As I said, its only a starting point, more useful checks can be added later.

for example some missing checks:
- check for $libdir (suffix missing) confusion - check for /usr/local anywhere - check for missing/inconsistent version in the .pc file

and many other things

Original comment by: scop

**Comment by scop** [comment]
CheckPkgConfig.py from original ticket: https://gist.github.com/scop/d1bd84d50041fb99eb07

**Comment by scarabeusiv** [comment]
Another part of the openSUSE patchset. Better version at https://github.com/openSUSE/rpmlint-checks/blob/master/CheckPkgConfig.py ; lets fix this one using the new issue #227
