### ISSUE TITLE
Update pypi 

### ISSUE THREAD

**Issue by StykMartin** [rpm-software-management/rpmlint#358]
Version uploaded in pypi is really obsolete - 0.48.
https://pypi.org/project/rpmlint/
Can you please upload the latest version there?
Thanks

**Comment by scarabeusiv** [comment]
It does not make much sense to be there at all. You won't be ever able to install it from there as it has deps on direct rpm bindings and other stuff.

Well I don't have access to remove it... Seems only Frederic Lepied can do so. Anyone has a contact info on him?

**Comment by Conan-Kudo** [comment]
@dmach I know Frederic left Red Hat, do you have the ability to do something about his PyPI registration of `rpmlint`?

**Comment by Conan-Kudo** [comment]
@scarabeusiv I'm attempting to reach to Frederic about this now.

**Comment by Conan-Kudo** [comment]
I now have ownership of the `rpmlint` package in PyPI, courtesy of Frederic.

**Comment by danigm** [comment]
The current version in pypi is `2.2.0`, it's not the latest release, but I think this issue can be closed.

**Comment by marxin** [comment]
@Conan-Kudo Can you please update the PyPI package to 2.4?
