### ISSUE TITLE
Missing specfile in upstream

### ISSUE THREAD

**Issue by StykMartin** [rpm-software-management/rpmlint#359]
Hi,

It is possible to maintain specfile also in upstream, so everyone can build rpmlint on their own?
This seems to be right way when pypi is no go (issue #358)

**Comment by Conan-Kudo** [comment]
@StykMartin I'm considering integrating a spec file and setting up Packit for this, yes. But I'm also considering uploading an artifact to PyPI when 2.0 is ready, too, even though it's not going to be terribly useful.

**Comment by StykMartin** [comment]
Sounds good, @Conan-Kudo. Thanks for information.

**Comment by scarabeusiv** [comment]
@Conan-Kudo I have the spec to build it from git in OBS:
 https://build.opensuse.org/package/view_file/home:scarabeus_iv:rpmlint-testbed/rpmlint/rpmlint.spec?expand=1

Feel free to base it from there, but TBH dunno if it really makes sense to provide actual spec...

**Comment by Conan-Kudo** [comment]
I'm not sure I really want to include a specfile in this project. If I were to do it, I want a nice, simple spec file that works across all distributions with few to no conditionals, leveraging things like commonly used virtual names. That's not likely to happen anytime soon because of issues in openSUSE...

**Comment by scarabeusiv** [comment]
Ok I will remove the milestone 2.0 for that then :-)

**Comment by mimi1vx** [comment]
@StykMartin any upstream spec file is really bad idea.

**Comment by StykMartin** [comment]
So you saying that pypi is bad idea, spec file is bad idea. How upstream community should build it? Waiting for you to make move?

**Comment by Conan-Kudo** [comment]
I own the PyPI project now, and I haven't decided which way I'm going to go for this.

Honestly, my blocker right now on an upstream spec file is that `python3dist()` dependencies aren't working in openSUSE yet. Once that's fully fixed, then I'd be willing to consider it.

**Comment by mimi1vx** [comment]
> So you saying that pypi is bad idea, spec file is bad idea. How upstream community should build it? Waiting for you to make move?

simply clone / download from github? + if you want spec/deb/ebuild write correct for your distribution?  and push to your distro?

**Comment by marxin** [comment]
Now we have a spec file for Packit project: `.packit/rpmlint.spec`.
@Conan-Kudo: Can we close the issue now?

**Comment by Conan-Kudo** [comment]
Yep! That should serve as a nice example file for everyone.
