### ISSUE TITLE
RFE: add "debug" option

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#37]
(From http://rpmlint.zarb.org/cgi-bin/trac.cgi/ticket/179, scop)

Copied from  https://bugzilla.redhat.com/show_bug.cgi?id=521628:

"Sometimes, it would be useful what checks is rpmlint actually doing, instead of just seeing the summary and the errors/warnings. Please add an option to allow "debugging", i.e. printing the name of each check that is run alongside with the criteria it has to meet (if applicable)."

This would be useful, however I think it'd also be quite a bit of work.

Changed 3 years ago by guest 

Would this will involve printing Info with printInfo as and when checks are executed and doing work the stuff.

Would doing it in stages be saner i.e first patch up for all checks that are executed and inform as [ OK ] if they are passed. Otherwise for failure it already prompts with corresponding messages. This first step would be easy.

Second one will go into more details for each Check. With more info messages. Would it make sense it do it in one big patch or check by check after review ?

Suggestions ?

rakesh rakesh@…

Changed 3 years ago by guest 

Hi scop, may you look into this when bit free :)

Thanks,

Changed 3 years ago by scop 

I think doing it in two or more steps would be good, with the first one using printDebug (not printInfo) with a "D" identifier just printing out checks as they are run.

Changed 3 years ago by guest 

version changed from 0.90 to trunk
milestone set to 0.94
I will look into it in coming days

thanks,

Original comment by: scop

**Comment by scarabeusiv** [comment]
With the change of the printout to be stored in the buffer and printed at the end it should not be done like the orginal comment here proposes.
I actually opened an issue because of a problem i had today #255 that explains how it could be done Today. So lets track it there.
