### ISSUE TITLE
[opensuse] review and port remainder of the rpmlint-checks that are SUSE specific to 2.0 syntax

### ISSUE THREAD

**Issue by scarabeusiv** [rpm-software-management/rpmlint#371]
When going over the review of what to port and review there still remain following items (counting open PRs as "done"):

openSUSE:
- [x] https://github.com/openSUSE/rpmlint-checks/blob/master/KMPPolicyCheck.py
- [x] https://github.com/openSUSE/rpmlint-checks/blob/master/BrandingPolicyCheck.py

Could be generalized, see https://github.com/rpm-software-management/rpmlint/blob/master/rpmlint/checks/PAMModulesCheck.py vs https://github.com/openSUSE/rpmlint-checks/blob/master/CheckPAMModules.py
- [x] https://github.com/openSUSE/rpmlint-checks/blob/master/CheckPolkitPrivs.py
- [x] https://github.com/openSUSE/rpmlint-checks/blob/master/CheckSUIDPermissions.py
- [x] https://github.com/openSUSE/rpmlint-checks/blob/master/CheckCronJobs.py
- [x] https://github.com/openSUSE/rpmlint-checks/blob/master/CheckDBUSServices.py

should be upstreamed:
- [x] https://github.com/openSUSE/rpmlint-checks/blob/master/LibraryPolicyCheck.py
- [x] https://github.com/openSUSE/rpmlint-checks/blob/master/CheckBuildRoot.py
- [x] https://github.com/openSUSE/rpmlint-checks/blob/master/ErlangCheck.py
- [x] https://github.com/openSUSE/rpmlint-checks/commits/master/MixedFileOwnerships.py

unless we manage to figure out a way how to make the test generic enough for the openSUSE ones they go only to opensuse branch, otherwise upstream first

**Comment by scarabeusiv** [comment]
BuildRoot was already done, I overlooked that 1e2d6e3abfb7419cd081df79b15c926228f2f052

**Comment by scarabeusiv** [comment]
KMPPolicyCheck is now WIP by me.

**Comment by scarabeusiv** [comment]
@Conan-Kudo what would be your opinion of https://github.com/openSUSE/rpmlint-checks/pull/55/files#diff-736af2f9cac9ffa626fddbff2dc31c73 I would say this suseism errorer could be upstream, so people by accident don't copy and add this?
I would of course extend it to check all other variables too not just supplements.

**Comment by Conan-Kudo** [comment]
@scarabeusiv Yeah, makes sense to me.

**Comment by Conan-Kudo** [comment]
I'd say that the zypp format would be "invalid" rather than "deprecated" in the upstream version, since it doesn't work for _most_ package managers.

**Comment by scarabeusiv** [comment]
The remaining checks are in pr#439 thus closing this ticket to move discussion about it there.
