### ISSUE TITLE
RFE: add documentation about which checks are run

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#38]
(From http://rpmlint.zarb.org/cgi-bin/trac.cgi/ticket/180, scop)

Copied from  https://bugzilla.redhat.com/show_bug.cgi?id=521622:

"While running rpmlint on a specfile and then on srpm the sets of spec tests differ. It is mentioned within the manpage and the readme file as CAVEATS:

"All checks do not apply to all argument types. For best check coverage, run rpmlint on source rpms instead of plain specfiles, and installed binary rpms instead of uninstalled binary rpm files."

But there is no list, or reference to other documentation, saying which checks apply for the particular input type. Please add some aid to tell what is going to be checked."

Original comment by: scop

**Comment by scarabeusiv** [comment]
Actually this sounds nice. Something like the printout that is done by pytest (header listing all the loaded tests, list of configs that are in use, then all the errors/warnings and at the end nice summary.
Pytest does it nicely so lets get some inspiration :)
