### ISSUE TITLE
Replace the large binary packages used for tests

### ISSUE THREAD

**Issue by scarabeusiv** [rpm-software-management/rpmlint#392]
We don't have the testing framework yet we still should not release anything really huge in the tarball -> use the obs to generate artifical tests instead of MB of real packages.

Current offenders are (I just took anything bigger than 200k and not already minimalized):
- [x] 2.8M Feb 11 15:09 binutils-devel-2.32-351.1.x86_64.rpm
- [x] 3.2M Jul  9  2018 cyrus-imapd-2.4.17-9.fc22.x86_64.rpm
- [x] 3.2M Jul  9  2018 dovecot-2.2.9-1.fc20.x86_64.rpm
- [x] 3.2M Feb 13 12:24 ruby-libs-2.7.0-1.fc32.x86_64.rpm
- [x] 517K Jul  9  2018 autofs-5.0.7-28.fc19.i686.rpm
- [x] 731K Sep 20  2018 mc-4.8.15-10.3.1.x86_64.rpm
- [x] 792K Sep 20  2018 mc-4.8.21-2.1.x86_64.rpm
- [x] 983K Feb 11 15:09 libreiserfscore-devel-3.6.27-0.x86_64.rpm

**Comment by Conan-Kudo** [comment]
Note that nobody else has an OBS to do this, so you have to keep in mind that everyone else is not necessarily going to be able to do that.

**Comment by Conan-Kudo** [comment]
It's not that I don't disagree that having these large RPMs is kind of insane, but nobody seems to be providing simple test cases that could be built using rpmbuild by the test apparatus.

**Comment by scarabeusiv** [comment]
The mc must stay as we use it for diff comparison, and you need full pkgs there.

**Comment by scarabeusiv** [comment]
Libreiserfs actually uses most of its size for the current test (like the data are used) so it does not make sense redoing it and getting same size out of it.
