### ISSUE TITLE
Check that %buildrequires is not inside %package

### ISSUE THREAD

**Issue by socketpair** [rpm-software-management/rpmlint#395]
I have not find official requirements of this, but in general, I saw completely wrong .spec-files where authors add some `builderequires` into `%package` subsection. They believe that this is better since these `buildrequires` are required only to build this subpackage. Since building of solely subpackage is not possible, I consider it wrong.

**Comment by Conan-Kudo** [comment]
BuildRequires in subpackages are a totally valid strategy, especially for organization and making easier to condition out subpackages and their necessary build dependencies.

**Comment by socketpair** [comment]
@Conan-Kudo but this is not documented anywhere. I mean if it is permitted or not.
