### ISSUE TITLE
allow packages with cron files to depend on "crontabs" instead of "cron"

### ISSUE THREAD

**Issue by thmo** [rpm-software-management/rpmlint#401]
https://github.com/rpm-software-management/rpmlint/blob/b592020f941e453dc523206f7127cb56a0b163b1/rpmlint/checks/FilesCheck.py#L565-L567

According to the [Fedora Packaging Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/CronFiles/), packages containing cron job files should depend on `crontabs`. The check should be updated to allow this.

**Comment by scarabeusiv** [comment]
On the other hand this is not applicable on others than Fedora.

Yet i.e. in openSUSE we now error if pkg installs cron instead of systemd timer...

**Comment by thmo** [comment]
> On the other hand this is not applicable on others than Fedora.

Would allowing `crontabs` in addition to `cron` as required dependency hurt the others?

> Yet i.e. in openSUSE we now error if pkg installs cron instead of systemd timer...

That's a different check, isn't it? Disallowing files `/etc/cron.*` in favor of systemd timers.

**Comment by Conan-Kudo** [comment]
We should be disallowing cron jobs by default on Fedora too. But the cron check should be updated to ensure require `crontabs` is a dependency.

**Comment by scarabeusiv** [comment]
Yep, it is different check, but the FilesCheck is not converted yet to the 'readable' layout of single functions. We might even say that because we want people on timers it is kinda pointless to check for cron otherwise.

**Comment by Conan-Kudo** [comment]
Indeed, that makes sense to me. We probably want to split cron checks out and add to the systemd check for preferring timers over cron jobs?

**Comment by Conan-Kudo** [comment]
@scarabeusiv It seems that in openSUSE, the `cron` package does the same thing as `crontabs` in Fedora, Mageia, OpenMandriva, and other distributions. That is, it provides the directory skeleton for installing cron jobs.

I can think of two ways to handle this:
* Add a duplicate check for `crontabs`
* Add `crontabs` Provides to `cron` package in openSUSE and adjust check accordingly.

**Comment by scarabeusiv** [comment]
We can live with crontabs provide in openSUSE. But tbh we really try to kill the cron usage and there should be almost none packages in Tumbleweed doing cron stuff.

**Comment by Conan-Kudo** [comment]
@scarabeusiv I agree, but given this, I'm going to propose a PR to adjust our check here.

**Comment by thmo** [comment]
Wow, that was quick. Thanks.
