### ISSUE TITLE
pytest error inside virtualenv

### ISSUE THREAD

**Issue by thisisshub** [rpm-software-management/rpmlint#408]
I was setting up the environment and following the readme [README.md](https://github.com/rpm-software-management/rpmlint/blob/master/README.md), I followed the step to [directly test](https://github.com/rpm-software-management/rpmlint/blob/master/README.md#directly) a test file and did a 
`python3 -m pytest test/test_config.py`

which led to the error 

> ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
> __main__.py: error: unrecognized arguments: --cov=rpmlint -n --flake8 test/test_config.py
>   inifile: /home/shub/devel/GSOC/rpmlint/setup.cfg
>   rootdir: /home/shub/devel/GSOC/rpmlint

**Comment by scarabeusiv** [comment]
Not a bug. The readme explicitly says you need pytest-cov and pytest-flake8 if you want to run the tests directly yourself.
