### ISSUE TITLE
tmpfiles.d check

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#41]
I found some packages in openSUSE that create files via system'd tmpfiles.d mechanism without having the files listed in %files. Some manage to evade other checks like the /var/lock check this way. So the attached patch adds a check that warns if tmpfiles are not in the file list.

Original comment by: l-n

**Comment by scop** [comment]
0001-add-check-for-tmpfiles-created-at-runtime.diff from original ticket: https://gist.github.com/scop/70bb1ed6061a49ffaf2e

**Comment by scarabeusiv** [comment]
This is tweaked and stored now in the SUSE repo and will be picked by the #227 , lets track it just there (this added patch is in worse  state than the one in the opensuse repo anyway).
