### ISSUE TITLE
Incorrect version information

### ISSUE THREAD

**Issue by losuler** [rpm-software-management/rpmlint#443]
I noticed in the [latest release](https://github.com/rpm-software-management/rpmlint/releases/tag/rpmlint-1.11) that the `-V, --version` flag reports it's version as 1.10 instead of 1.11.

**Comment by scarabeusiv** [comment]
As we are more near the release 2.0 I don't think it makes much sense to re-tag year and half old release just to fix the version field. Thanks for the report tho if there would be any other useful commit in 1.11 branch it would make sense, but as of now it seems people can live with the wrong info for a bit longer there.
