### ISSUE TITLE
Add new check for wrongly specified version in Requires

### ISSUE THREAD

**Issue by socketpair** [rpm-software-management/rpmlint#449]
i.e. check for this:

`Requires: xxxx=yyy`
or
`Requires: xxxx>=yyy`

Actually user wanted spaces around comparison operator. Without spaces, RPM considers whole string as a package name.

**Comment by scarabeusiv** [comment]
We have this already in spec-cleaner to format it so rpmlint can safely ignore it as it should be fixed by other tool in the rpm arsenal.
