### ISSUE TITLE
Support gem.build_complete file

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpmlint#462]
Each rubygem-patckage with binary extension ship empty `gem.build_complete` file which is required by RubyGems to detect that binary extension was built, therefore it would be nice if rpmlint have not complained about this file.

~~~
$ rpmlint rubygem-puma-4.3.6-1.fc34.x86_64.rpm 
rubygem-puma.x86_64: E: zero-length /usr/lib64/gems/ruby/puma-4.3.6/gem.build_complete
rubygem-puma.x86_64: W: no-manual-page-for-binary pumactl
1 packages and 0 specfiles checked; 1 errors, 1 warnings.
~~~

**Comment by scarabeusiv** [comment]
This should be fairly trivial, we can have list of known zero files that need to be on fs, like py.typed is empty and expected as another alternative.
