### ISSUE TITLE
name-repeated-in-summary emits stray "C"

### ISSUE THREAD

**Issue by jengelh** [rpm-software-management/rpmlint#538]
(Happens in the rpmlint2-based openSUSE:Factory:Staging:M/AppStream)

```
[  139s] AppStream.x86_64: W: name-repeated-in-summary C AppStream
[  139s] AppStream.src: W: name-repeated-in-summary C AppStream
[  139s] The name of the package is repeated in its summary. Make the summary brief and
[  139s] to the point without including redundant information in it.
```

I never understood why there is a "C" or what it is supposed to mean. Can we remove it, lest it be replaced by something meaningful?

**Comment by scarabeusiv** [comment]
Sure, the C is the language

https://github.com/rpm-software-management/rpmlint/blob/master/rpmlint/checks/TagsCheck.py#L197

**Comment by marxin** [comment]
I'm going to fix it.
