### ISSUE TITLE
Remove linebreak from branding-requires-unversioned message

### ISSUE THREAD

**Issue by jengelh** [rpm-software-management/rpmlint#540]
(rpmlint2 from openSUSE:Factory:Staging:M/ModemManager)

```
[  157s] ModemManager-devel.x86_64: W: incoherent-version-dependency-on ModemManager*/ModemManager-libs/libModemManager* 1.12.10 None:1.12.10
[  157s] ModemManager.x86_64: E: branding-requires-unversioned hicolor-icon-theme
[  157s] Please make sure that your requires entry is similar to: 'Requires: %name-
[  157s] branding = <versionnumber>'
```

Most other lines are as long as they want to be; wrapping, if anything, is left to the terminal.
Can the linebreak after `%name-` be removed so that the branding-requires-unversioned warning looks coherent?

**Comment by scarabeusiv** [comment]
Actually this is spewing from Textwrap usage for the descriptions.

As the toml has it right:
https://github.com/rpm-software-management/rpmlint/blob/opensuse/rpmlint/descriptions/BrandingPolicyCheck.toml#L13
