### ISSUE TITLE
fix utf8 checks

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#6]
(From http://rpmlint.zarb.org/cgi-bin/trac.cgi/ticket/147, dmueller@suse.de)

the utf8 checks do not work properly on rpm tags, because the rpm bindings return the data in the C locale. in order to make them return the data in the user's locale, the localisation has to be initalized. this is done with this call:

locale.setlocale(locale.LC_ALL, )

see documentation of the locale module on python.org.

scop: 

Could you post a complete reproducer (rpm or link to one, locale settings, output)? I'm not sure how to try reproducing this, but I do see eg. tag-not-utf8 warnings eg. for summaries that contain non-UTF-8 characters.

scop:

Still waiting for a reproducer...

Original comment by: scop

**Comment by scop** [comment]
Diff: https://gist.github.com/scop/177087a6c505f3ada7fb

**Comment by scarabeusiv** [comment]
This in its own should be now fixes as the whole rpmlint operates in utf8 namespace.
