### ISSUE TITLE
Crash with non ascii characters

### ISSUE THREAD

**Issue by susnux** [rpm-software-management/rpmlint#61]
If there are non ascii / utf8 characters in the message rpmlint crashes.
E.g. in my case a "non-utf8-filename" warning with latin1 characters:

    [  377s] Traceback (most recent call last):
    [  377s]   File "rpmlint.py", line 385, in &lt;module&gt;
    [  377s]   File "rpmlint.py", line 196, in main
    [  377s]   File "Filter.py", line 131, in printAllReasons
    [  377s]   File "Filter.py", line 40, in __print
    [  377s]   File "/usr/lib/python2.7/codecs.py", line 357, in write
    [  377s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 56: ordinal not in range(128)

A simple fix, but maybe not perfect would be:
http://pastebin.com/uN36hKnL

**Comment by scop** [comment]
There is no `non-utf8-filename` warning, did you mean `filename-not-utf8`? Also, the traceback looks a bit odd, we don't ship a `rpmlint.py` file either but just `rpmlint`. Is this with a customized rpmlint?

But most importantly, I tried to construct a test package but was not very successful, could you let me know where can I get the package you found the issue with?

**Comment by susnux** [comment]
Yes sorry I meant ```filename-not-utf8```.
I use the rpmlint package from openSUSE

**Comment by scop** [comment]
Ok, but more importantly, what package are you checking with rpmlint when you encounter the issue?

**Comment by susnux** [comment]
E.g. this one:
https://build.opensuse.org/package/show/devel:libraries:c_c++/aspell-dictionaries
at current revision revision 47.
(there is a pending request which will fix the causing issues)

**Comment by scop** [comment]
So I started browsing from that page, trying to find a package that contains non-UTF-8 filenames, and found e.g. this: http://download.opensuse.org/repositories/devel:/libraries:/c_c%2B%2B/openSUSE_Factory/i586/aspell-nb-0.50.10-94.1.i586.rpm

I don't get a crash when rpmlinting that with the current rpmlint master branch, neither with python 2 or 3. I just see the UTF-8 replacement character:

```
$ rpmlint ./aspell-nb-0.50.10-94.1.i586.rpm | grep filename
aspell-nb.i586: E: filename-not-utf8 /usr/lib/aspell-0.60/bokm�l.alias
```

This is also visible in the "rpmlint results" tab in the URL you posted, there's no crash in it either for filename-not-utf8.

Ìf this is not one of the packages that you get a crash with, please give me a direct URL to a rpm file that you do see it with.

**Comment by susnux** [comment]
It seems to only appear if you try to write to file not a tty:

    /tmp/rpmlint (git)-[master] % ./rpmlint ~/Downloads/aspell-nb-0.50.10-94.1.i586.rpm > foo.txt                                             :(
    Traceback (most recent call last):
      File "./rpmlint", line 371, in <module>
        main()
      File "./rpmlint", line 160, in main
        runChecks(pkg)
      File "./rpmlint", line 217, in runChecks
        check.check(pkg)
      File "/tmp/rpmlint/FilesCheck.py", line 408, in check
        printError(pkg, 'filename-not-utf8', b2s(filename))
      File "/tmp/rpmlint/Filter.py", line 53, in printError
        _print("E", pkg, reason, details)
      File "/tmp/rpmlint/Filter.py", line 94, in _print
        __print(s)
      File "/tmp/rpmlint/Filter.py", line 41, in __print
        print(s, file=__stdout)
      File "/usr/lib64/python2.7/codecs.py", line 351, in write
        data, consumed = self.encode(object, self.errors)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 62: ordinal not in range(128)

**Comment by scop** [comment]
Reproduced, thanks. Also, it seems to happen only with Python 2.

**Comment by scop** [comment]
Code in https://github.com/rpm-software-management/rpmlint/blob/master/Filter.py#L37 exists specifically in order to deal with this issue. I fail to see why it doesn't -- `errors` gets set to `replace` but despite of that the codec seems to behave as it if was set to `strict`. And why does the error message say `ascii` when we've set up `__stdout` using a UTF-8 `StreamWriter`...?

**Comment by Fak3** [comment]
The problem is that "s" passed to __print() is object of type "str", not "unicode". Calling s.encode('utf-8') will actually have to decode that "str" to "unicode" (using ascii by default), and then encode resulting "unicode" to utf-8. So this will result in s.decode('ascii').encode('utf-8'). If "s" is a string, that was encoded with, say 'utf-8', then decoding it with 'ascii' will fail with the error (on first non-ascii character)
So the fix should be to decode "s" first with appropriate encoding, to get proper "unicode" object. Most likely all strings that are passed to this __print() finction can be decoded using sys.getfilesystemencoding()

**Comment by LazyKent** [comment]
I got the same crash.
```
[   73s] RPMLINT report:
[   73s] ===============
[   76s] outwiker.noarch: W: zero-length /usr/share/outwiker/help/help_en/Page Types/Wiki Page/Wiki Commands/childlist command/page 2/__page.text
[   76s] 2 packages and 0 specfiles checked; 0 errors, 20 warnings.
[   76s] Traceback (most recent call last):
[   76s]   File "rpmlint.py", line 385, in <module>
[   76s]   File "rpmlint.py", line 196, in main
[   76s]   File "Filter.py", line 131, in printAllReasons
[   76s]   File "Filter.py", line 40, in __print
[   76s]   File "/usr/lib/python2.7/codecs.py", line 357, in write
[   76s]     data, consumed = self.encode(object, self.errors)
[   76s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 65: ordinal not in range(128)
```
The package is: https://build.opensuse.org/package/show/home:Lazy_Kent/outwiker

**Comment by scop** [comment]
I don't think the cases that actually provoke this crash (non-UTF-8 filenames on UTF-8 systems) would be decodable using `sys.getfilesystemencoding()`.

**Comment by Fak3** [comment]
Why do you think that non-UTF-8 filenames provoke the crash? They may be UTF-8. But still you have to explicitly decode it with utf-8. Otherwise ascii is used and you got a crash.
My proposal to decode it in the "__print" function is quite dirty approach. The correct way will be to use only unicode objects throughout all the project, and in those places, where some os.* function returns you str object, immediately decode it with sys.getfilesystemencoding()

**Comment by scop** [comment]
Wrt non-UTF-8, well, that's what is reported in this issue. Maybe it occurs with some others too. I agree that using unicode everywhere would be a good fix, but that's pretty far away.

**Comment by Fak3** [comment]
Ah, right - if the string really has non-utf8 encoding, then in the dirty solution you can specify 'replace' error handling:

    def __print(s):
         print(s.decode('utf-8', 'replace'), file=__stdout)

**Comment by Fak3** [comment]
The problem raised by outwiker is not 'filename-not-utf8', it crashes in the 'cross-directory-hard-link':

```
u1@pc1:/home/z/pproj/rpmlint> ./rpmlint -c FilesCheck /tmp/build-root//home/abuild/rpmbuild/RPMS/noarch/outwiker-1.8.1-0.noarch.rpm | tee
0 packages and 0 specfiles checked; 0 errors, 1 warnings.
Traceback (most recent call last):
  File "./rpmlint", line 371, in <module>
    main()
  File "./rpmlint", line 160, in main
    runChecks(pkg)
  File "./rpmlint", line 217, in runChecks
    check.check(pkg)
  File "/home/z/pproj/rpmlint/FilesCheck.py", line 537, in check
    printWarning(pkg, 'cross-directory-hard-link', f, hardlink)
  File "/home/z/pproj/rpmlint/Filter.py", line 53, in printWarning
    _print("W", pkg, reason, details)
  File "/home/z/pproj/rpmlint/Filter.py", line 98, in _print
    __print(s)
  File "/home/z/pproj/rpmlint/Filter.py", line 45, in __print
    print(s, file=__stdout)
  File "/usr/lib64/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 158: ordinal not in range(128)
```
Filenames there are correctly encoded with ut8.
So this is a problem with printing any non-ascii string. (including utf-8)

The original bugreport is about the case when the string to be printed is neither ascii, nor utf8.
