### ISSUE TITLE
Drop rcfoo checks in openSUSE branch

### ISSUE THREAD

**Issue by hellcp** [rpm-software-management/rpmlint#624]
With SLE 15 SP2 the [support for System V init.d scripts has been marked as deprecated](https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP2/#jsc-SLE-7690). For both Tumbleweed and Leap/SLE 16 that means that the checks associated with that functionality should also be deprecated and dropped.

**Comment by marxin** [comment]
Fixed on `opensuse` branch.
