### ISSUE TITLE
equivalent of setFilterException

### ISSUE THREAD

**Issue by dirkmueller** [rpm-software-management/rpmlint#660]
SUSE's rpmlint 1.x had a downstream patch to implement `setFilterException` 

this was used in the config packages to make certain checks non-filterable by the package included rpmlintrcs:

`./rpmlint-Factory/config:setFilterException('suse-dbus-unauthorized-service')`

how is that now working within rpmlint 2.x?

**Comment by Conan-Kudo** [comment]
We do not have an equivalent of that feature. I'm not sure it even makes sense to have one. What's the value of that when you already have a policy to not have rpmlintrc files for packages going into Factory?

**Comment by marxin** [comment]
> What's the value of that when you already have a policy to not have rpmlintrc files for packages going into Factory?

That's not feasible for `openSUSE:Factory` where we have ~1000 packages using `rpmlintrc` file (out of 13K packages).

**Comment by Conan-Kudo** [comment]
This seems like a policy failure, then. Rpmlint shouldn't be used in this manner, because it has all kinds of crappy knock-on effects for users.

If you want policies people can't ignore, then you should just implement them separately or in a different mechanism (e.g. [rpminspect](https://github.com/rpminspect/rpminspect)).

**Comment by marxin** [comment]
> This seems like a policy failure, then. Rpmlint shouldn't be used in this manner, because it has all kinds of crappy knock-on effects for users.

I'm not sure we ever had a policy that would disallow `rpmlintrc` files. Anyway, we can't handle it easily now :)

> 
> If you want policies people can't ignore, then you should just implement them separately or in a different mechanism (e.g. [rpminspect](https://github.com/rpminspect/rpminspect)).

Sounds good. It seems to me very similar for GCC compiler warnings. We have gazillion of them in openSUSE:Factory and it's unlikely people will some of them.

**Comment by dirkmueller** [comment]
> Sounds good. It seems to me very similar for GCC compiler warnings. We have gazillion of them in openSUSE:Factory and it's unlikely people will some of them.

thats why rpmlint (1.x here) is checking for the policy incompliant warnings and fails them. 

the idea of having this done as early as possible means the original submitter sees it. it is possible to use rpminspect etc at a later stage for official projects, but thats already 3 - 4 steps down the line which need to be unwound when something is discovered there.

**Comment by Conan-Kudo** [comment]
> it is possible to use rpminspect etc at a later stage for official projects, but thats already 3 - 4 steps down the line which need to be unwound when something is discovered there.

Well, there's nothing that stops you from running them on everything and just only making rpminspect hard-fail by default on Factory. OBS supports running things after it gets the finished build.
