### ISSUE TITLE
W: hidden-file-or-dir /usr/share/cargo/registry/*/.cargo-checksum.json

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpmlint#699]
All Fedora rust packages warn with:

    W: hidden-file-or-dir /usr/share/cargo/registry/.../.cargo-checksum.json

Can we please exclude this file from the check? It seems to be legitimate. (Unfortunately, I have not familiarized myself with the new way of rpmlint configuration.)

Thanks.

**Comment by marxin** [comment]
The easiest way would be adding them after this rule:
https://github.com/rpm-software-management/rpmlint/blob/8a29e612ae4d9b21fbdf8abed9526315bc2be224/configs/Fedora/fedora.toml#L276

**Comment by hroncok** [comment]
Is this *Fedora specific stuff that we don't want*? Shouldn't this be filtered everywhere?

**Comment by marxin** [comment]
Sure, I can prepare a patch for it.
