### ISSUE TITLE
Would be useful to check that .so files have execute permission

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#7]
I was just packaging something for Fedora and having trouble with a failing dependency on a shared library in a subpackage. Turns out that upstream's "make install" installs the shared library without execute permissions, but rpmlint didn't product any error or warning about it.

It would be useful for rpmlint to check for that, (including versioned .so files) and report an error.

Original comment by: brouhaha

**Comment by marxin** [comment]
Lemme work on that.

**Comment by marxin** [comment]
Well, I see really a huge number of shared libraries with executable bit set:

`
marxin@marxinbox:~> find /usr/lib64 -type f -executable | grep '\.so' | wc -l
7538
marxin@marxinbox:~> find /lib64 -type f -executable | grep '\.so' | wc -l
128
marxin@marxinbox:~> find /lib -type f -executable | grep '\.so' | wc -l
94
`

That said, I don't see the check much interesting.

**Comment by marxin** [comment]
@scarabeusiv Please drop `Milestone 2.0`.

**Comment by marxin** [comment]
@scarabeusiv I would close it as we went in with #286?

**Comment by scarabeusiv** [comment]
Okay. I am still chatting with the toolchain guys about the need for it but makes sense.
