### ISSUE TITLE
RFE: check gobject-introspection files

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpmlint#74]
```
addFilter(".*devel-file-in-non-devel-package.*/usr/share/gir-1.0/*\.gir")
```

something like this.. and opposite

`%{libdir}/girepository-1.0/*.typelib` should go not in devel pkg

**Comment by scop** [comment]
I'm not familiar with gi packaging, can you point me at some references regarding this? Looks like in current Fedora all *.gir are in -devel packages, but there are a bunch of devel packages shipping *.typelib and before adding a check, I would like some confirmation that these are in fact packaging bugs, i.e. that it's always the case that *.gir should go in devel and *.typelib not.

```
$ dnf whatprovides "*.typelib" | grep devel
libabiword-1:3.0.1-10.fc23.x86_64 : Library for developing applications based on
nntpgrab-devel-0.7.2-12.fc23.i686 : Development files for NNTPGrab
nntpgrab-devel-0.7.2-12.fc23.x86_64 : Development files for NNTPGrab
signon-glib-devel-1.9-4.fc23.i686 : Development files for signon-glib
signon-glib-devel-1.9-4.fc23.x86_64 : Development files for signon-glib
webkitgtk4-jsc-devel-2.12.1-1.fc23.i686 : Development files for JavaScript
webkitgtk4-jsc-devel-2.12.1-1.fc23.x86_64 : Development files for JavaScript
bamf-devel-0.5.0-6.fc23.i686 : Development files for bamf
bamf-devel-0.5.0-6.fc23.x86_64 : Development files for bamf
imsettings-devel-1.6.8-6.fc23.i686 : Development files for imsettings
imsettings-devel-1.6.8-6.fc23.x86_64 : Development files for imsettings
libabiword-1:3.0.1-4.fc23.x86_64 : Library for developing applications based on
libdmapsharing-devel-2.9.30-3.fc23.i686 : Libraries/include files for
libdmapsharing-devel-2.9.30-3.fc23.x86_64 : Libraries/include files for
nntpgrab-devel-0.7.2-10.fc23.i686 : Development files for NNTPGrab
nntpgrab-devel-0.7.2-10.fc23.x86_64 : Development files for NNTPGrab
sugar-runner-0.106.0-1.fc23.i686 : Sugar runner emulator for development
sugar-runner-0.106.0-1.fc23.x86_64 : Sugar runner emulator for development
```

**Comment by ignatenkobrain** [comment]
so, `.gir` is just XML file which is used I think when you compile another GI. Usually you use `--include=GObject-2.0` to include another packages which I think will use `.gir` file.

`.typelib` is binary and is used in runtime (e.g. you have in python `from gi.repository import GLib`).

So looks like those few packages (7 actually) have wrong packaging. I'm very surprised about webkit (8th) so I checked:
```
[ignatenko@ignatenko rpmlint]$ rpm -ql webkitgtk4-jsc | grep typelib
/usr/lib64/girepository-1.0/JavaScriptCore-4.0.typelib
[ignatenko@ignatenko rpmlint]$ rpm -ql webkitgtk4-jsc-devel | grep typelib
/usr/lib64/girepository-1.0/JavaScriptCore-4.0.typelib
```

Which means also packaging error ;)

**Comment by ignatenkobrain** [comment]
http://pkgs.fedoraproject.org/cgit/rpms/webkitgtk4.git/commit/?id=511ddd84e544d9f8625af26d91c98f58cfe6bade

**Comment by ignatenkobrain** [comment]
@scop thanks a lot!
