### ISSUE TITLE
Check for executable stack broken on various architectures

### ISSUE THREAD

**Issue by Vogtinator** [rpm-software-management/rpmlint#762]
On `ppc64le`, pretty much all binaries fail the `missing-PT_GNU_STACK-section` check because rpmlint assumes that this section is required to prevent getting an executable stack.

However, this section is only required on some architectures, where the default is to have an executable stack. On architectures which have a non-executable stack by default, this section is not required. That should also be the default for new architectures, so I'd suggest to make a list of architectures where the `GNU_STACK` section is required. This can be checked in glibc by looking at the value of `DEFAULT_STACK_PERMS` for that architecture.

**Comment by marxin** [comment]
Thanks for the analysis, I can work on that.
