### ISSUE TITLE
wrong-script-interpreter FILE /usr/bin/env zsh

### ISSUE THREAD

**Issue by Fale** [rpm-software-management/rpmlint#78]
It seems like the wrong-script-interpreter thinks that 

    #!/usr/bin/env zsh

is an invalid shabang. It seems legit to me

**Comment by scop** [comment]
`/usr/bin/env` (well actually `env`, no matter which path it is in) is not a valid interpreter for rpm-packaged software per rpmlint's rules. Use an explicit path to the exact actual interpreter you want. Or if you disagree, it is possible to filter the message out with something like `addFilter("wrong-script-interpreter .* /usr/bin/env")` in your rpmlint config.
