### ISSUE TITLE
no-library-dependency-for misreported for -devel package

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpmlint#781]
Checking ruby-devel package rpmlint reports following error:

~~~
ruby-devel.x86_64: E: no-library-dependency-for /usr/lib64/libruby.so.3.1.0
~~~

And these are the requires:

~~~
 rpm -qpR /var/lib/mock/ruby/result/ruby-devel-3.1.0-1.fc36.x86_64.rpm
/usr/bin/pkg-config
libruby.so.3.1()(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
ruby(x86-64) = 3.1.0-1.fc36
rubygems
~~~

I believe that this dependency is sufficiently satisfied by `libruby.so.3.1()(64bit)`:

~~~
$ rpm -qpP /var/lib/mock/ruby/result/ruby-libs-3.1.0-1.fc36.x86_64.rpm | grep 'libruby.so.3.1()(64bit)'
libruby.so.3.1()(64bit)
~~~

So why rpmlint still complains?

**Comment by marxin** [comment]
I must confess this check is a bit misleading. It only works when also `ruby-libs-3.1.0-1.fc36.x86_64.rpm` is also checked, because only then the check can verify the symlink target and really identify the file is provided by the `ruby-libs` package.

**Comment by marxin** [comment]
Doing `./lint.py /tmp/ruby-devel-3.1.0-1.fc36.x86_64.rpm /tmp/ruby-libs-3.1.0-1.fc36.x86_64.rpm`, you can see however a different error:

```
ruby-devel.x86_64: E: no-library-dependency-on ruby-libs /usr/lib64/libruby.so.3.1.0
```

that one is caused by wrong parsing of `libruby.so.3.1()(64bit)` that is not parsed at all. Lemme take a look.

**Comment by voxik** [comment]
Ah, these are different. I have not noticed. But I was testing the two together initially, so there is probably something wrong ;)

**Comment by marxin** [comment]
> libruby.so.3.1()(64bit)

Well, the check expects here usage of `ruby-libs`, why do you hardcode SONAME here?

**Comment by voxik** [comment]
This is dependency is pregenerated by RPM

**Comment by marxin** [comment]
I see. I would likely recommend disabling the checks for Fedora, it's quite SUSE-specific.

**Comment by voxik** [comment]
I have reported this against Fedora:

https://bugzilla.redhat.com/show_bug.cgi?id=2037402

Unfortunately, I don't know where is the right place to disable the check to be able to open PR against Fedora

**Comment by marxin** [comment]
Just add it to Filters: https://github.com/rpm-software-management/rpmlint/blob/79f0e738565d4d774b55ef49186cf38d182f3d53/configs/Fedora/fedora.toml#L65

**Comment by voxik** [comment]
This was implemented in Fedora:

https://src.fedoraproject.org/rpms/rpmlint/c/73ebf18e2ca7650aea82f5690051ae7b89c2f031?branch=rawhide
