### ISSUE TITLE
shared-library-not-executable only checks libs with INTERP set

### ISSUE THREAD

**Issue by Vogtinator** [rpm-software-management/rpmlint#792]
https://github.com/rpm-software-management/rpmlint/blob/74e205295fc57d2d36e328ed953eb16549447b97/rpmlint/checks/BinariesCheck.py#L500-L503

The text says that RPM might not look at libraries without executable permission set.

However, rpmlint only checks the few shared libraries which have an `INTERP` set.

Either the text is wrong and RPM doesn't look at the +x bit or the check should be adjusted.

**Comment by marxin** [comment]
It's me who added the `INTERP` check in #286. It really does not make sense reporting the error only for 'INTERP' shlibs.

**Comment by marxin** [comment]
Can't remember any such discussion, let's simplify the check then.
