### ISSUE TITLE
RFE: check comments on patches

### ISSUE THREAD

**Issue by scop** [rpm-software-management/rpmlint#8]
(From http://rpmlint.zarb.org/cgi-bin/trac.cgi/ticket/182)

Does it make sense to check whether patches have any comments (which could be links also and we can check if they can be accessed) mentioned along with it which explains it ?
- Rakesh Pandit

Original comment by: scop

**Comment by scarabeusiv** [comment]
We in openSUSE have this lovely lenghty policy for patches explaining what to do with them, how to annotate, what comments/format/...
Honestly most of the time it is ignored and the same would apply here. If we would print out anything it can be only Info or Warning and not many people would care about it.
I would like to see this unified but checking the openSUSE tree the policy is respected in <20% cases...
