### ISSUE TITLE
has_early_fail_option typo in BashismsCheck?

### ISSUE THREAD

**Issue by jirislaby** [rpm-software-management/rpmlint#802]
Looking at the code from commit 92fca3389ac27fb168a97e199b754d5bf3dbb133:
https://github.com/rpm-software-management/rpmlint/blob/cc4678201f40283a49c3d506067502ff54079a49/rpmlint/checks/BashismsCheck.py#L15-L19

Is `has_early_fail_option` a typo? Shouldn't it be `use_early_fail`? Maybe I just don't follow the code...

**Comment by marxin** [comment]
Yep, thanks for the heads up. Btw. what were you seeking during reading rpmlint's source code?

**Comment by jirislaby** [comment]
@marxin bsc#1195955 :)

**Comment by marxin** [comment]
Oh, cool. I'm going to take a look next week, I'm officially off this week.
Anyway, thanks for working on that.
