### ISSUE TITLE
rpmlint not working on macos

### ISSUE THREAD

**Issue by ssbarnea** [rpm-software-management/rpmlint#803]
It seems that it is not specified the fact the rpmlint does not work on macos and likely other many other UNIX platforms.

Package metadata lists UNIX and for a python project, one can expect it to work. When I tried to install it I got:
```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/pip-install-v99rqfx8/rpm_cea2d1739dc24bd79df83deb8cc1f649/setup.py", line 8, in <module>
          raise RuntimeError("Install aborted - please install python-rpm from distribution system.")
      RuntimeError: Install aborted - please install python-rpm from distribution system.
      [end of output]
```

I do also understand that the tool is likely to ever work only on a very limited set of distributions, but that should be stated and we should also provide a way to skip running it on unsupported platforms.

I was looking on enabling use of rpmlint as part of my [pre-commit](https://pre-commit.com/) hooks but there is no option to skip a hook on unsupported platforms. Still, I want to run it on system where it can be run (like a graceful degradation of the testing).

Probably the solution would to to not prevent installation on unsupported platform and to do a runtime check when the tools starts. We could even added flag like `--skip-unsupported` which would allow rpmlint to return success when rpm tooling is missing from current system (like macos).

Let me know what you think.

**Comment by marxin** [comment]
> raise RuntimeError("Install aborted - please install python-rpm from distribution system.")

The tool is supposed to work on MacOS system. And one needs to install the requires package `python-rpm`.
Please take a look at the mandatory prerequisites:
https://github.com/rpm-software-management/rpmlint#install

**Comment by marxin** [comment]
Closing as there's not reply and I'm pretty sure it's about missing dependencies.
