### ISSUE TITLE
DNF does not work for openSUSE

### ISSUE THREAD

**Issue by marxin** [rpm-software-management/rpmlint#826]
Can be seen here:
https://github.com/rpm-software-management/rpmlint/runs/5448485012?check_suite_focus=true

@Conan-Kudo: Can you please take a look?

**Comment by Conan-Kudo** [comment]
Looks like mirror failure... 😩

**Comment by Conan-Kudo** [comment]
@marxin I give up with MirrorBrain and I'm fixing it for Leap 15.4 and Tumbleweed now:

* Tumbleweed: https://build.opensuse.org/request/show/968036
* Leap 15.4: https://build.opensuse.org/request/show/968037
