### ISSUE TITLE
FYI: rpmlint version 1 container

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/rpmlint#828]
This ticket is just for your information.

On Fedora project, a gating CI called Zuul CI is running rpmlint 1.11 in the Fedora 34 container. While on Fedora 35+, the rpmlint is version 2. We still want to run rpmlint version 1 on local environment. So, I just prepare the container file to run the rpmlint 1 on local.

https://github.com/junaruga/rpmlint1-container

**Comment by marxin** [comment]
> We still want to run rpmlint version 1 on local environment.

Can you please consider switching to rpmlint 2.x ? Note rpmlint 1.x is pretty legacy and unsupported.

**Comment by junaruga** [comment]
Yes, Zuul CI team is willing to switch to rpmlint 2.x in Zuul CI. Here is the issue ticket.
https://pagure.io/fedora-ci/general/issue/332
