### ISSUE TITLE
Differentiate between warnings and errors with --strict

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/rpmlint#843]
With `--strict` it would be nice to know if rpmlint found warnings or errors.  Having a different, non-0 exit codes for warnings vs. errors would be the desired mechanism.

**Comment by brianjmurrell** [comment]
Hrm.  I'm not sure #844 accomplishes the request.

How do I know that only warnings were found?

**Comment by marxin** [comment]
> How do I know that only warnings were found?

Return value `65` will be returned, if there will be an error, then `64` exit code is used.

**Comment by brianjmurrell** [comment]
Oh, yes.  I see now.  Thanks for the info!
