### ISSUE TITLE
Unable to use a single rpmlintrc for both spec and binary RPMs

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/rpmlint#855]
If I have a binary RPM that triggers `package-with-huge-docs` from rpmlint and so then add `addFilter("package-with-huge-docs") ` to `rpmlintrc` to allow that, when I then try to use that same `rpmlintrc` when linting the specfile I get a different error: `E: unused-rpmlintrc-filter "package-with-huge-docs"`.  But even trying to ignore that with an additional `addFilter('unused-rpmlintrc-filter')` in the `rpmlintrc` file doesn't allow the one `rpmlintrc` file to be used with both the binary RPMs and specfile.

How should this be handled?

**Comment by marxin** [comment]
https://github.com/rpm-software-management/rpmlint/pull/795#issuecomment-1118476973
