### ISSUE TITLE
Please work to maintain interface compatibility going forward

### ISSUE THREAD

**Issue by portante** [rpm-software-management/rpmlint#887]
When `rpmlint` switched from v1.x to v2.x the `--file` switch was changed to `--rpmlintrc` (see 733c6fdf5786f00c6d68d058717794e35a5521d7).

No compatibility was maintained with the older versions, so that when one is working with `rpmlint` across distributions which offer different versions of this command, operational compatibility is a royal pain.

One such workaround can be found at: https://github.com/distributed-system-analysis/pbench/pull/2900.

In the future, please, please work at maintaining CLI interface compatibility.

See PR #888.

**Comment by marxin** [comment]
Sure, sorry about the pain we caused.

**Comment by portante** [comment]
The new code is great, but the various distributions are quite slow on the uptake.  E.g. Fedora 36 recently updated to `2.2.0`, but Fedora 35 and early was pre-`2.0.0`.

**Comment by marxin** [comment]
Thanks. Yeah, it takes time for adopters, but `2.x` is released more than a year ago.

**Comment by marxin** [comment]
May I close this issue or is there anything we can do more now?

**Comment by portante** [comment]
You used to process the command line arguments this way:

https://github.com/rpm-software-management/rpmlint/commit/733c6fdf5786f00c6d68d058717794e35a5521d7#diff-7648dc3c10ba77f88603c69e93f08b450312cf122de18d82a884af5ac562252cL252

And changed it to:

https://github.com/rpm-software-management/rpmlint/commit/733c6fdf5786f00c6d68d058717794e35a5521d7#diff-b876009dba1465dc07811a58ada657a0683327f88b04ef02bb0ff2a4b07ca19eR74

Reviewing the two different argument switches to identify what else can be aliased and / or notified for compatibility might be worth the effort.

**Comment by marxin** [comment]
May I please close this or is there any other difference?
