### ISSUE TITLE
Add cassandra user to standrard users

### ISSUE THREAD

**Issue by trepik** [rpm-software-management/rpmlint#89]
When I run rpmlint on my package I get this warning:
cassandra.x86_64: W: non-standard-uid /var/log/cassandra cassandra
I think the solution is adding cassandra to the standard users list but I could not figure out where I should do it. Anyone could give me a clue?

**Comment by scop** [comment]
If you're using rpmlint shipped by your distro, please file an issue against the distro package. We ship a very minimal list in rpmlint and most likely will not be adding new entries to it. But if you want just your local config to have it, see the `StandardUsers` configuration option.
