### ISSUE TITLE
Change logic of file version checking

### ISSUE THREAD

**Issue by deekej** [rpm-software-management/rpmlint#90]
Hello people,
I'm resubmitting the bug/feature request from Red Hat's Bugzilla [#1399683](https://bugzilla.redhat.com/show_bug.cgi?id=1399683) here:

At the moment, *rpmlint* will complain (display warning) about **unversioned-explicit-provides** for a file with absolute path. If you try to fix this by adding the `%{version}`, then checking again with rpmlint leads to:
`specfile-error error: line 11: Versioned file name not permitted`

The logic of this does not make any sense, and it should be changed, either in the code, or preferably in some default configuration of *rpmlint*.

*rpmlint shouldnt warn that something is wrong when fix would cause an error instead...*

And before we get to the discussion that specfile should not contain the **Provides** with absolute path, I need to tell you that for some packages in Fedora this is really necessary (and most likely always will be). For example, I'm taking care of *tcsh*, which as a shell was always placed as /bin/tcsh. This is no longer true because of [*UsrMove*](https://fedoraproject.org/wiki/Features/UsrMove) in Fedora, but we need to keep that **Provides** in the specfile because of backwards compatibility.

As a result, I always see an unnecessary warning in Fedora's [Bodhi](https://bodhi.fedoraproject.org/) infrastructure after **dist.rpmlint** check.

#### Steps to Reproduce:
1. Create a specfile containing `'Provides: /bin/tcsh = %{version}'`
2. Run *rplint* on the specfile.

#### Actual results:
Misleading warning about `unversioned-explicit-provides /bin/tcsh`

#### Expected results:
No warning about `unversioned-explicit-provides /bin/tcsh'`

**Comment by scop** [comment]
Warning disabled now, thanks for the report. I see no reason to make this one configurable, but remember that unwanted messages from rpmlint can always be filtered out using `addFilter` in your personal or your distro's default config.

**Comment by deekej** [comment]
@scop Thank you for pointing that out. I wasn't aware of that. I was forwarded here from Fedora's BZ. I will mention there the option `addFilter` for default config, and for our Bodhi infrastructure as well, if needed. :)
