### ISSUE TITLE
Increased shlib-policy-name-error strictness breaks many HPC packages

### ISSUE THREAD

**Issue by StefanBruens** [rpm-software-management/rpmlint#901]
https://github.com/rpm-software-management/rpmlint/commit/0f2d40caf7f7e1f6e637c3f4f4d32791b5b05037

This is definitely a change that should have been announced on the Factory mailing list prior to merging it.

The science repository now has about 200 extra failing packages (about 40-50 source packages) and it is not clear how to solve this.

Although the MPI and HPC flavors reside in a separate namespace (filesystem prefix), the SLPP still applies for each flavor, so we *must* have a guideline which also covers these packages before applying such a policy.

There are three possible patterns for the library name:
1. `lib<name><versionsuffix><flavor>`
2. `lib<name><flavor><versionsuffix>`
3. `<flavor>lib<name><versionsuffix>`

Each of these patterns complies with the idea (co-installability) of the [SLPP](https://en.opensuse.org/openSUSE:Shared_library_packaging_policy), though not with its current wording.

(1.) is the one currently used by the HPC/MPI flavors. Rejected by rpmlint, as the `versionsuffix` must be the last fragment.
(2.) would pass rpmlint, but requires renaming (with extra Provides/Obsoletes) *all* affected packages
(3.) is the one currently used by e.g. mingw packages. These are completely ignored by rpmlint (package name not starting with `lib`)

**Comment by marxin** [comment]
> This is definitely a change that should have been announced on the Factory mailing list prior to merging it.

Sure, we should have done that. One the other hand we had quite an intensive discussion with @e4t who was aware of the intention.

> 
> The science repository now has about 200 extra failing packages (about 40-50 source packages) and it is not clear how to solve this.

All right, so is there an easy way how can we identify the HPC libraries (of the current format `lib<name><versionsuffix><flavor>`) so that we can special-case the SLPP check in rpmlint?

**Comment by marxin** [comment]
@jengelh

**Comment by marxin** [comment]
Ok, so the libraries are under the following 2 locations: `/usr/lib64/mpi` and `/usr/lib/hpc/`.
I'm ready for disabling of the check for these locations and if you want you can adjust the SLPP check in order to understand the HPC naming scheme.

**Comment by marxin** [comment]
> For i586/armv7, the first one is `/usr/lib/mpi/`.

I see, PR updated accordingly.

**Comment by simotek** [comment]
Yes but skipping the check for two hardcoded locations isn't really scalable into the future, maybe a better solution would be a slightly different warning with a much lower badness score for libraries not in the standard search paths like `/usr/lib64`

**Comment by StefanBruens** [comment]
> See the discussion in: #849
> 
> @marxin: You ought've taken my concerns serious and not gone ahead merging this.
> 
> Frankly, I don't see a point to perform this check for any library outside the default search path.

IMHO, the SLPP in general applies to *all* packages, HPC, MPI flavors, serial, or whatever.

The only difference is the means to achieve this, and how the rpmlint check has to look.

1. The HPC packages have the package version as part of the filesystem prefix, and thus *do* comply with the SLPP - make multiple versions co-installable.
2. The MPI flavors have separate prefixes for the MPI variant (MVAPICH, openMPI{2,3,4}), but install into the same directory regardless of package version. Incompatible versions must have distinct soversions (in the library as well as in the package name). Only one version per SOVERSION can be installed.

So, for the HPC packages, the rpmlint check is not really necessary. For the MPI flavors, the check is actually useful (though, as the check is at least run for the serial flavor, packaging bugs are likely catched there).

**Comment by marxin** [comment]
> Yes but skipping the check for two hardcoded locations isn't really scalable into the future, maybe a better solution would be a slightly different warning with a much lower badness score for libraries not in the standard search paths like `/usr/lib64`

As @StefanBruens wrote, we should not report a misleading warning for a format the rpmlint check does not understand.

**Comment by marxin** [comment]
> So, for the HPC packages, the rpmlint check is not really necessary. For the MPI flavors, the check is actually useful (though, as the check is at least run for the serial flavor, packaging bugs are likely catched there).

All right, so I'm going to merge the skipping for now in order to unblock the very many failures in `Factory` and feel free to come up with a pull request where you'll handle the MPI flavors.
