### ISSUE TITLE
New feature SCLCheck check "set -e" in scl macro

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/rpmlint#92]
In the case of Software Collection, I want to check if "set -e" exists inside of `scl` macro, if the lines are >= 2 by `rpmlint`.

Because "set -e" is important regarding below document, to catch an error inside of `scl` macro.

https://www.softwarecollections.org/en/docs/guide/#sect-Converting_RPM_Scripts

> It is important to specify set -e in the script so that the script behavior is consistent regardless of whether the script is executed in the rpm shell or the scl environment. 

Below case does not need "set -e".

```
%{?scl:scl enable %{scl} - << \EOF}
echo aaa
%{?scl:EOF}
```

However below case needs "set -e" to catch an error for "echo bbb".

```
%{?scl:scl enable %{scl} - << \EOF}
echo aaa
echo bbb
%{?scl:EOF}
```

Is it possible to add this check (maybe to SCLCheck.py)?

Thank you.

**Comment by junaruga** [comment]
Hi,
I prepared a script `check_scl_set_e` that may be hint to implement this in `rpmlint`, though I did not implement it for `rpmlint` by myself.
https://gist.github.com/junaruga/b9270cdefad7a53d3e6aacfd4f7ccd74

The scripts check whether `set -e` exists in line number >=2 for each `scl` macro.
For example, below `rubygem-single_test.spec`
http://pkgs.fedoraproject.org/cgit/rpms/rubygem-single_test.git/tree/rubygem-single_test.spec

```
$ ~/scripts/check_scl_set_e rubygem-single_test.spec
rubygem-single_test.spec:[OK][1] (<= result, line number inside of scl macro)
rubygem-single_test.spec:[OK][1]
rubygem-single_test.spec:[OK][1]
rubygem-single_test.spec:[NG][6]
```

If we will insert 'set -e' after line 69 `%{?scl:scl enable %{scl} - << \EOF}` in the `rubygem-single_test.spec`, the "NG" result becomes "OK".

**Comment by scarabeusiv** [comment]
We ripped out sclcheck due to being unmaintained from rpmlint, as such I am closing this bug as wontfix.
