### ISSUE TITLE
Should an /etc/ld.so.conf.d/* file really be a configuration file?

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/rpmlint#924]
`daos.x86_64: W: non-conffile-in-etc /etc/ld.so.conf.d/daos.conf` I think is telling me that I should be flagging that file as a `%config` file, but should it really be?  It's not something the admin should [want] to edit.

Indeed, probably there ought to be a `/usr/lib/ld.so.conf.d/` dir by recent convention, but I don't think that exists so we **have** to use `/etc/ld.so.conf.d/`

**Comment by marxin** [comment]
@DimStar77, @Vogtinator: Can you please comment on this?

**Comment by Vogtinator** [comment]
It indeed shouldn't be marked as `%config`. IMO `ld.so.conf` shouldn't be needed anyway, there's no real advantage compared to just putting the libs into `%_libdir`.

`/usr/lib/ld.so.conf.d` could be implemented by adding `include /usr/lib/ld.so.conf.d/*.conf` to `ld.so.conf`.

**Comment by brianjmurrell** [comment]
> It indeed shouldn't be marked as `%config`. IMO `ld.so.conf` shouldn't be needed anyway, there's no real advantage compared to just putting the libs into `%_libdir`.

My understanding is that unversioned, private shared libs should not be put into `%_libdir` but somewhere private to the package and `/etc/ld.so.conf.d/*` is exactly for telling the runtime linker where they are.

> `/usr/lib/ld.so.conf.d` could be implemented by adding `include /usr/lib/ld.so.conf.d/*.conf` to `ld.so.conf`.

Sure, but that still ends up being a change that a package has to make as it's not a standard part of a distribution, so it ends up being the same kind of change as is being flagged by this ticket.

**Comment by DimStar77** [comment]
> > It indeed shouldn't be marked as `%config`. IMO `ld.so.conf` shouldn't be needed anyway, there's no real advantage compared to just putting the libs into `%_libdir`.
> 
> My understanding is that unversioned, private shared libs should not be put into `%_libdir` but somewhere private to the package and `/etc/ld.so.conf.d/*` is exactly for telling the runtime linker where they are.

As soon as you have an /etc/ld.so.conf.d entry, the libs are no longer private and can are found by the linker - for every single binary looking for a library with this name.

Private libraries (outside of the global linker space) is implemented using rpath/runpath in binaries or LD_LIBRARY_PATH variables in a wrapper script
