### ISSUE TITLE
FilelistCheck points to inaccessible bugzilla.novell.com bug

### ISSUE THREAD

**Issue by StefanBruens** [rpm-software-management/rpmlint#932]
https://github.com/rpm-software-management/rpmlint/blob/1a7345a13a29895063e79e3e59388c3d8851c846/rpmlint/descriptions/FilelistCheck.toml#L30

1. The bug should be publicly accessible (also reported on Factory ML)
2. bugzilla.novell.com should be bugzilla.suse.com

**Comment by marxin** [comment]
Fixed now. Thanks for the report.

**Comment by bmwiedemann** [comment]
URL Fix: https://github.com/openSUSE/rpmlint-checks/pull/70
